### ISSUE TITLE
installation failed

### ISSUE THREAD

**Issue by nitinkumarmishra** [mgechev/angular2-seed#1011]
hi @mgechev,
I am getting following installation error.

[12:39:42] Requiring external module ts-node/register
TSError: ⨯ Unable to compile TypeScript
typings/browser/definitions/xhr2/xhr2.d.ts (166,1): Duplicate identifier 'export='. (2300)
typings/browser/definitions/xhr2/xhr2.d.ts (170,1): Duplicate identifier 'export='. (2300)
typings/main/definitions/xhr2/xhr2.d.ts (166,1): Duplicate identifier 'export='. (2300)
typings/main/definitions/xhr2/xhr2.d.ts (170,1): Duplicate identifier 'export='. (2300)
    at getOutput (/Users/nitin/Sites/projects/angular2-seed-rc-2/node_modules/ts-node/src/ts-node.ts:210:13)
    at Object.loader (/Users/nitin/Sites/projects/angular2-seed-rc-2/node_modules/ts-node/src/ts-node.ts:225:23)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (/Users/nitin/Sites/projects/angular2-seed-rc-2/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/Users/nitin/Sites/projects/angular2-seed-rc-2/node_modules/gulp/node_modules/liftoff/index.js:193:16)
    at module.exports (/Users/nitin/Sites/projects/angular2-seed-rc-2/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/Users/nitin/Sites/projects/angular2-seed-rc-2/node_modules/gulp/node_modules/liftoff/index.js:185:9)

npm ERR! Darwin 15.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 postinstall: `typings install && gulp check.versions && npm prune && gulp webdriver`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed@0.0.0 postinstall script 'typings install && gulp check.versions && npm prune && gulp webdriver'.
npm ERR! This is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install && gulp check.versions && npm prune && gulp webdriver
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nitin/Sites/projects/angular2-seed-rc-2/npm-debug.log

**Comment by gotenxds** [comment]
Same here

**Comment by ckapilla** [comment]
I had those errors until I did a fresh git clone into a new directory and npm install and that took care of it

**Comment by juristr** [comment]
happens to me also with a fresh clone.

```
node v5.6.0
npm  v3.6.0
```

**Comment by juristr** [comment]
oh, sorry...probably got it. Take a look at this: https://github.com/mgechev/angular2-seed/issues/453#issuecomment-181889953

You need to make sure that you delete the "old" typings folders. Like I did a

```
$ rm -rf typings
$ rm -rf tools/typings
```

Followed by a fresh `typings install` and then `gulp check.versions`. Should run then.
