### ISSUE TITLE
Running inside docker is not working

### ISSUE THREAD

**Issue by anho** [mgechev/angular2-seed#1018]
I'm not sure if this is an issue with the codebase of the project, from Angular or Node inside docker itself. Maybe someone has solved this or a similar issue already in the past and is now able to enlighten me.

**Steps to reproduce the problem**
Run the docker image (I chose node 4.4 here as it is the recommended version in the Readme):
````
docker run -it --rm -p "8003:8080" -w /usr/src/app node:4.4-wheezy bash
````

To be sure, these are the versions of node & npm:
````
root@273b848e6bcf:/usr/src/app# node -v
v4.4.5
root@273b848e6bcf:/usr/src/app# npm -v
2.15.5
````

Then inside docker run the steps from the Readme:
````
git clone --depth 1 https://github.com/mgechev/angular2-seed.git
cd angular2-seed
// use @angular/router@3.0.0-alpha.7 instead of @angular/router@3.0.0-alpha.6
npm install
npm start -- --port 8080
````

It aborts the startup with the following error:

````
> angular2-seed@0.0.0 start /usr/src/app/angular2-seed
> gulp serve.dev --color "--port" "8080"

[14:52:14] Requiring external module ts-node/register
TSError: ⨯ Unable to compile TypeScript
gulpfile.ts (1,23): Cannot find module 'gulp'. (2307)
gulpfile.ts (2,30): Cannot find module 'run-sequence'. (2307)
// snip lots of errors
tools/utils/seed/watch.ts (3,30): Cannot find module 'run-sequence'. (2307)
    at getOutput (/usr/src/app/angular2-seed/node_modules/ts-node/src/ts-node.ts:210:13)
    at Object.loader (/usr/src/app/angular2-seed/node_modules/ts-node/src/ts-node.ts:225:23)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (/usr/src/app/angular2-seed/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/src/app/angular2-seed/node_modules/gulp/node_modules/liftoff/index.js:193:16)
    at module.exports (/usr/src/app/angular2-seed/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/src/app/angular2-seed/node_modules/gulp/node_modules/liftoff/index.js:185:9)
````

**Comment by xvs32x** [comment]
@anho  npm install gulp ? :)

**Comment by xvs32x** [comment]
@anho  not sure, but it may install gulp globally

**Comment by mgechev** [comment]
@anho would you try with globally installed `typings`? It is related to issues finding ambient type defs.

**Comment by mgechev** [comment]
@anho any updates?

**Comment by anho** [comment]
@mgechev unfortunately no success with your or the recommendation from @xvs32x. Other suggestions?

**Comment by mgechev** [comment]
@anho here's another suggestion https://github.com/mgechev/angular2-seed/issues/930#issuecomment-228528152.

**Comment by anho** [comment]
@mgechev many thanks, that did the trick 👍 Plus this works well with newer versions of node as well.
