### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by frehil** [mgechev/angular2-seed#1079]
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.10.3
3 info using node@v4.4.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle angular2-seed@0.0.0~prestart: angular2-seed@0.0.0
6 silly lifecycle angular2-seed@0.0.0~prestart: no script for prestart, continuing
7 info lifecycle angular2-seed@0.0.0~start: angular2-seed@0.0.0
8 verbose lifecycle angular2-seed@0.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-seed@0.0.0~start: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/home/fhill/angular2-seed/node_modules/.bin:/usr/local/bin:/opt/OpenPrinting-Gutenprint/sbin:/opt/OpenPrinting-Gutenprint/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/jvm/java-8-oracle/bin:/usr/lib/jvm/java-8-oracle/db/bin:/usr/lib/jvm/java-8-oracle/jre/bin
10 verbose lifecycle angular2-seed@0.0.0~start: CWD: /home/fhill/angular2-seed
11 silly lifecycle angular2-seed@0.0.0~start: Args: [ '-c', 'gulp serve.dev --color' ]
12 silly lifecycle angular2-seed@0.0.0~start: Returned: code: 1  signal: null
13 info lifecycle angular2-seed@0.0.0~start: Failed to exec start script
14 verbose stack npm start
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:827:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid angular2-seed@0.0.0
16 verbose cwd /home/fhill/angular2-seed
17 error Linux 3.13.0-59-generic
18 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
19 error node v4.4.1
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error angular2-seed@0.0.0 start: `gulp serve.dev --color`
22 error Exit status 1
23 error Failed at the angular2-seed@0.0.0 start script 'gulp serve.dev --color'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-seed package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp serve.dev --color
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-seed
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-seed
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by bogdanmanate** [comment]
I can confirm this issue. My npm start command is failing at the same gulp task.
It seems that there is a problem with ts-node module. I'm investigating this issue and I will keep this thread updated.

**Comment by mgechev** [comment]
Here's a related issue https://github.com/mgechev/angular2-seed/issues/359.

What are your OS, npm and node versions?

**Comment by bogdanmanate** [comment]
@mgechev The solutions mentioned issue #359 solved my problem. Maybe the npm cache clear command should be included in the installing instructions. I don't think that will cause any harm.

**Comment by mgechev** [comment]
Cleaning the cache is a bit too invasive. We'll keep it as fix suggestion for now.
