### ISSUE TITLE
npm install failed

### ISSUE THREAD

**Issue by alexlevy0** [mgechev/angular2-seed#1095]
Hello, I can't setup whith npm install.
thank in advance

```
npm verb afterAdd C:\Users\alexl\AppData\Roaming\npm-cache\typings\0.7.12\package\package.json written
npm info git [ 'rev-list', '-n1', 'master' ]
npm verb resolveHead git+https://github.com/floridoo/gulp-sourcemaps.git#master resolved Git URL: git+https://github.com/floridoo/gulp-sourcemaps.git#f0acd2a31150b0403c14eed53e6234b192704257
npm info git [ 'clone',
npm info git   'C:\\Users\\alexl\\AppData\\Roaming\\npm-cache\\_git-remotes\\git-https-github-com-floridoo-gulp-sourcemaps-git-master-520f67c20f34e4496852db2d91c31eed',
npm info git   'C:\\Users\\alexl\\AppData\\Local\\Temp\\npm-4148-6cb70a7e\\git-cache-7287710f5d6c1eca83b4781f567da3fe\\f0acd2a31150b0403c14eed53e6234b192704257' ]
npm ERR! git clone C:\Users\alexl\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-floridoo-gulp-sourcemaps-git-master-520f67c20f34e4496852db2d91c31eed C:\Users\alexl\AppData\Local\Temp\npm-4148-6cb70a7e\git-cache-7287710f5d6c1eca83b4781f567da3fe\f0acd2a31150b0403c14eed53e6234b192704257: Cloning into 'C:\Users\alexl\AppData\Local\Temp\npm-4148-6cb70a7e\git-cache-7287710f5d6c1eca83b4781f567da3fe\f0acd2a31150b0403c14eed53e6234b192704257'...
npm ERR! git clone C:\Users\alexl\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-floridoo-gulp-sourcemaps-git-master-520f67c20f34e4496852db2d91c31eed C:\Users\alexl\AppData\Local\Temp\npm-4148-6cb70a7e\git-cache-7287710f5d6c1eca83b4781f567da3fe\f0acd2a31150b0403c14eed53e6234b192704257: fatal: '/cygdrive/c/Users/alexl/AppData/Roaming/npm-cache/_git-remotes/git-https-github-com-floridoo-gulp-sourcemaps-git-master-520f67c20f34e4496852db2d91c31eed/C:\Users\alexl\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-floridoo-gulp-sourcemaps-git-master-520f67c20f34e4496852db2d91c31eed' does not appear to be a git repository
npm ERR! git clone C:\Users\alexl\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-floridoo-gulp-sourcemaps-git-master-520f67c20f34e4496852db2d91c31eed C:\Users\alexl\AppData\Local\Temp\npm-4148-6cb70a7e\git-cache-7287710f5d6c1eca83b4781f567da3fe\f0acd2a31150b0403c14eed53e6234b192704257: fatal: Could not read from remote repository.
npm ERR! git clone C:\Users\alexl\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-floridoo-gulp-sourcemaps-git-master-520f67c20f34e4496852db2d91c31eed C:\Users\alexl\AppData\Local\Temp\npm-4148-6cb70a7e\git-cache-7287710f5d6c1eca83b4781f567da3fe\f0acd2a31150b0403c14eed53e6234b192704257:
npm ERR! git clone C:\Users\alexl\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-floridoo-gulp-sourcemaps-git-master-520f67c20f34e4496852db2d91c31eed C:\Users\alexl\AppData\Local\Temp\npm-4148-6cb70a7e\git-cache-7287710f5d6c1eca83b4781f567da3fe\f0acd2a31150b0403c14eed53e6234b192704257: Please make sure you have the correct access rights
npm ERR! git clone C:\Users\alexl\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-floridoo-gulp-sourcemaps-git-master-520f67c20f34e4496852db2d91c31eed C:\Users\alexl\AppData\Local\Temp\npm-4148-6cb70a7e\git-cache-7287710f5d6c1eca83b4781f567da3fe\f0acd2a31150b0403c14eed53e6234b192704257: and the repository exists.
npm ERR! git clone C:\Users\alexl\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-floridoo-gulp-sourcemaps-git-master-520f67c20f34e4496852db2d91c31eed C:\Users\alexl\AppData\Local\Temp\npm-4148-6cb70a7e\git-cache-7287710f5d6c1eca83b4781f567da3fe\f0acd2a31150b0403c14eed53e6234b192704257:
npm verb stack Error: Command failed: git -c core.longpaths=true clone C:\Users\alexl\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-floridoo-gulp-sourcemaps-git-master-520f67c20f34e4496852db2d91c31eed C:\Users\alexl\AppData\Local\Temp\npm-4148-6cb70a7e\git-cache-7287710f5d6c1eca83b4781f567da3fe\f0acd2a31150b0403c14eed53e6234b192704257
npm verb stack Cloning into 'C:\Users\alexl\AppData\Local\Temp\npm-4148-6cb70a7e\git-cache-7287710f5d6c1eca83b4781f567da3fe\f0acd2a31150b0403c14eed53e6234b192704257'...
npm verb stack fatal: '/cygdrive/c/Users/alexl/AppData/Roaming/npm-cache/_git-remotes/git-https-github-com-floridoo-gulp-sourcemaps-git-master-520f67c20f34e4496852db2d91c31eed/C:\Users\alexl\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-floridoo-gulp-sourcemaps-git-master-520f67c20f34e4496852db2d91c31eed' does not appear to be a git repository
npm verb stack fatal: Could not read from remote repository.
npm verb stack
npm verb stack Please make sure you have the correct access rights
npm verb stack and the repository exists.
npm verb stack
npm verb stack     at ChildProcess.exithandler (child_process.js:202:12)
npm verb stack     at emitTwo (events.js:100:13)
npm verb stack     at ChildProcess.emit (events.js:185:7)
npm verb stack     at maybeClose (internal/child_process.js:827:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb cwd C:\Dev\angular2-seed-sass
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\alexl\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "i" "--loglevel" "verbose"
npm ERR! node v5.7.0
npm ERR! npm  v3.3.10
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone C:\Users\alexl\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-floridoo-gulp-sourcemaps-git-master-520f67c20f34e4496852db2d91c31eed C:\Users\alexl\AppData\Local\Temp\npm-4148-6cb70a7e\git-cache-7287710f5d6c1eca83b4781f567da3fe\f0acd2a31150b0403c14eed53e6234b192704257
npm ERR! Cloning into 'C:\Users\alexl\AppData\Local\Temp\npm-4148-6cb70a7e\git-cache-7287710f5d6c1eca83b4781f567da3fe\f0acd2a31150b0403c14eed53e6234b192704257'...
npm ERR! fatal: '/cygdrive/c/Users/alexl/AppData/Roaming/npm-cache/_git-remotes/git-https-github-com-floridoo-gulp-sourcemaps-git-master-520f67c20f34e4496852db2d91c31eed/C:\Users\alexl\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-floridoo-gulp-sourcemaps-git-master-520f67c20f34e4496852db2d91c31eed' does not appear to be a git repository
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Dev\angular2-seed-sass\npm-debug.log
C:\Dev\angular2-seed-sass [master ≡]
λ
```

**Comment by mgechev** [comment]
Would you try `npm cache clean` and `npm i` again?

**Comment by TheDonDope** [comment]
> npm ERR! Command failed: git -c core.longpaths=true clone C:\Users\alexl\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-floridoo-gulp-sourcemaps-git-master-520f67c20f34e4496852db2d91c31eed C:\Users\alexl\AppData\Local\Temp\npm-4148-6cb70a7e\git-cache-7287710f5d6c1eca83b4781f567da3fe\f0acd2a31150b0403c14eed53e6234b192704257
> npm ERR! Cloning into 'C:\Users\alexl\AppData\Local\Temp\npm-4148-6cb70a7e\git-cache-7287710f5d6c1eca83b4781f567da3fe\f0acd2a31150b0403c14eed53e6234b192704257'...
npm ERR! fatal: '/cygdrive/c/Users/alexl/AppData/Roaming/npm-cache/_git-remotes/git-https-github-com-floridoo-gulp-sourcemaps-git-master-520f67c20f34e4496852db2d91c31eed/C:\Users\alexl\AppData\Roaming\npm-cache\_git-remotes\git-https-github-com-floridoo-gulp-sourcemaps-git-master-520f67c20f34e4496852db2d91c31eed' does not appear to be a git repository
> npm ERR! fatal: Could not read from remote repository.

Looks like a networking error. Not related to the seed itself!
