### ISSUE TITLE
not able to do npm run build.prod

### ISSUE THREAD

**Issue by vivdkool** [mgechev/angular2-seed#1096]
hi not able to do build production

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/vitiwary/.nvm/versions/node/v6.2.0/bin/node',
1 verbose cli   '/Users/vitiwary/.nvm/versions/node/v6.2.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build.prod' ]
2 info using npm@3.8.9
3 info using node@v6.2.0
4 verbose run-script [ 'prebuild.prod', 'build.prod', 'postbuild.prod' ]
5 info lifecycle angular2-seed@0.0.0~prebuild.prod: angular2-seed@0.0.0
6 silly lifecycle angular2-seed@0.0.0~prebuild.prod: no script for prebuild.prod, continuing
7 info lifecycle angular2-seed@0.0.0~build.prod: angular2-seed@0.0.0
8 verbose lifecycle angular2-seed@0.0.0~build.prod: unsafe-perm in lifecycle true
9 verbose lifecycle angular2-seed@0.0.0~build.prod: PATH: /Users/vitiwary/.nvm/versions/node/v6.2.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/vitiwary/Documents/workSpaces/ise_scale_poc/angular2_seed/node_modules/.bin:/Users/vitiwary/.nvm/versions/node/v6.2.0/bin:/Users/vitiwary/.nvm/versions/node/v6.2.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
10 verbose lifecycle angular2-seed@0.0.0~build.prod: CWD: /Users/vitiwary/Documents/workSpaces/ise_scale_poc/angular2_seed
11 silly lifecycle angular2-seed@0.0.0~build.prod: Args: [ '-c', 'gulp build.prod --color' ]
12 silly lifecycle angular2-seed@0.0.0~build.prod: Returned: code: 1  signal: null
13 info lifecycle angular2-seed@0.0.0~build.prod: Failed to exec build.prod script
14 verbose stack Error: angular2-seed@0.0.0 build.prod: `gulp build.prod --color`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/vitiwary/.nvm/versions/node/v6.2.0/lib/node_modules/npm/lib/utils/lifecycle.js:245:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/vitiwary/.nvm/versions/node/v6.2.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid angular2-seed@0.0.0
16 verbose cwd /Users/vitiwary/Documents/workSpaces/ise_scale_poc/angular2_seed
17 error Darwin 15.5.0
18 error argv "/Users/vitiwary/.nvm/versions/node/v6.2.0/bin/node" "/Users/vitiwary/.nvm/versions/node/v6.2.0/bin/npm" "run" "build.prod"
19 error node v6.2.0
20 error npm  v3.8.9
21 error code ELIFECYCLE
22 error angular2-seed@0.0.0 build.prod: `gulp build.prod --color`
22 error Exit status 1
23 error Failed at the angular2-seed@0.0.0 build.prod script 'gulp build.prod --color'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the angular2-seed package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp build.prod --color
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs angular2-seed
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls angular2-seed
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by mgechev** [comment]
Duplication of https://github.com/mgechev/angular2-seed/issues/359.
