### ISSUE TITLE
Can't install the seed 

### ISSUE THREAD

**Issue by giovapanasiti** [mgechev/angular2-seed#1170]
When I try to run npm start after following all others instructions I got this error:

Can anyone please help me? 

```

> angular2-seed@0.0.0 start /Users/giovanni/angular2-seed
> gulp serve.dev --color

[19:16:36] Requiring external module ts-node/register

/Users/giovanni/angular2-seed/node_modules/ts-node/src/index.ts:259
          throw new TSError(diagnosticList)
                ^
TSError: ⨯ Unable to compile TypeScript
gulpfile.ts (1,23): Cannot find module 'gulp'. (2307)
gulpfile.ts (2,23): Cannot find module 'gulp-util'. (2307)
gulpfile.ts (3,30): Cannot find module 'run-sequence'. (2307)
    at getOutput (/Users/giovanni/angular2-seed/node_modules/ts-node/src/index.ts:259:17)
    at /Users/giovanni/angular2-seed/node_modules/ts-node/src/index.ts:268:16
    at Object.compile (/Users/giovanni/angular2-seed/node_modules/ts-node/src/index.ts:404:17)
    at loader (/Users/giovanni/angular2-seed/node_modules/ts-node/src/index.ts:290:33)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/giovanni/angular2-seed/node_modules/ts-node/src/index.ts:307:14)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Liftoff.handleArguments (/Users/giovanni/angular2-seed/node_modules/gulp/bin/gulp.js:116:3)

npm ERR! Darwin 15.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.4.3
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 start: `gulp serve.dev --color`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-seed@0.0.0 start script 'gulp serve.dev --color'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve.dev --color
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/giovanni/angular2-seed/npm-debug.log
```

**Comment by mgechev** [comment]
Did you run `npm install` first?
