### ISSUE TITLE
cannot switch environment using --config-env flag

### ISSUE THREAD

**Issue by calvinhmw** [mgechev/angular2-seed#1215]
I'm trying to run the angular2-seed starter project in production mode. So I do `npm start -- --config-env prod`. But it still tries to run in development environment and I also got:
```

> angular2-seed@0.0.0 start /Users/mhu/angular2-seed
> gulp serve.dev --color --config-env dev "--config-env" "prod"

```
```
[22:16:01] TypeError: Path must be a string. Received [ 'dev', 'prod' ]
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:479:5)
    at getConfig (/Users/mhu/angular2-seed/tools/utils/seed/template_locals.ts:8:22)
    at Object.templateLocals (/Users/mhu/angular2-seed/tools/utils/seed/template_locals.ts:29:18)
    at module.exports (/Users/mhu/angular2-seed/tools/tasks/seed/build.js.dev.ts:61:28)
    at Gulp.<anonymous> (/Users/mhu/angular2-seed/tools/utils/seed/tasks_tools.ts:32:31)
    at module.exports (/Users/mhu/angular2-seed/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/mhu/angular2-seed/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/mhu/angular2-seed/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/mhu/angular2-seed/node_modules/orchestrator/index.js:134:8)
```

Isn't it supposed to execute the `gulp serve.prod` command instead ?

**Comment by mgechev** [comment]
You can use "npm run serve.prod". "config-env" is for setting the environment configuration.

**Comment by calvinhmw** [comment]
Does the config-env flag also sets environment configuration for build process ? My production build needs to extract the production API endpoint form the config.json file. Can I do `npm run build.prod -- --config-env prod` ?

**Comment by TheDonDope** [comment]
You do not need to pass `--config-env prod`, since `build.prod` already does that for you: https://github.com/mgechev/angular2-seed/blob/master/package.json#L12

So you just need to run `$ npm run build.prod` and you are good to go! :)

**Comment by calvinhmw** [comment]
Doesn't seem to work for me. I did `npm run build.prod`. But in my main.ts I have:
if ('<%= ENV %>' === 'prod') {
  enableProdMode();
  console.log('<%= ENV %>');
}
In production environment it still shows it's in dev environment.
