### ISSUE TITLE
[Error: EMFILE: too many open files] with karma new feature -> run test.watch

### ISSUE THREAD

**Issue by edud69** [mgechev/angular2-seed#1233]
Hi guys,

With the new command introduced lately `npm run test.watch` with a reasonable amount of source-files in your project, you can get _[Error: EMFILE: too many open files]_.

```
    21 08 2016 07:53:04.674:ERROR [karma]: { [Error: EMFILE: too many open files, open '
--PATH_TO_SRC--)\gulp-watch\node_modules\chokidar\node_modules\readdirp\stream-api.js']
  errno: -4066,
  code: 'EMFILE',
  syscall: 'open',
  path: '--PATH_TO_SRC--)\\node_modules\\gulp-watch\\node_modules\\chokidar\\node_modules\\readdirp\\stream-api.js' }`

`Error: EMFILE: too many open files, open '--PATH_TO_SRC--)\node_modules\gulp-watch\node_modules\chokidar\node_modules\readdirp\stream-api.js'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.Module._extensions..js (module.js:415:20)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at readdir (--PATH_TO_SRC--)\node_modules\gulp-watch\node_modules\chokidar\node_modules\readdirp\readdirp.js:55:25)
    at FSWatcher.<anonymous> (--PATH_TO_SRC--)\node_modules\gulp-watch\node_modules\chokidar\lib\nodefs-handler.js:355:5)
    at FSWatcher.NodeFsHandler._handleDir (--PATH_TO_SRC--)\node_modules\gulp-watch\node_modules\chokidar\lib\nodefs-handler.js:406:18)
    at FSWatcher.<anonymous> ((--PATH_TO_SRC--)\node_modules\gulp-watch\node_modules\chokidar\lib\nodefs-handler.js:455:19)
    at FSWatcher.<anonymous> (--PATH_TO_SRC--)\node_modules\gulp-watch\node_modules\chokidar\lib\nodefs-handler.js:460:16)
    at FSReqWrap.oncomplete (fs.js:82:15)
```

**Solution:**
It seems to be an OS-related problem. It seems by default, the file limit is set at 256 (type command `ulimit -n`). Running the command `ulimit -n 10480` will fix the problem, but the downside is that you have to do it everytime (changes are not persistent).

Should we introduce this command in the seed (maybe it could be configurable)?

Thanks

**Comment by mgechev** [comment]
Ah, I see. Thanks a lot for the issue and the solution! What we can do is to update the README.md file with this information. Do you want to open a PR?

**Comment by mgechev** [comment]
I guess we can close the issue for now.
