### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined at flattenGlob

### ISSUE THREAD

**Issue by karlhaas** [mgechev/angular2-seed#1236]
Hi!
We are using angular2-seed and today after i deleted node_modules and re-installed all packages, I got the following error during the build process:
```
[12:20:57] 'build.js.dev' errored after 167 ms
[12:20:57] TypeError: Cannot read property 'length' of undefined
    at flattenGlob (/home/karl/Work/cnc/feedbackr/Frontend/node_modules/glob2base/index.js:9:25)
    at setToBase (/home/karl/Work/cnc/feedbackr/Frontend/node_modules/glob2base/index.js:48:12)
    at module.exports (/home/karl/Work/cnc/feedbackr/Frontend/node_modules/glob2base/index.js:56:19)
    at Object.gs.createStream (/home/karl/Work/cnc/feedbackr/Frontend/node_modules/glob-stream/index.js:34:42)
    at /home/karl/Work/cnc/feedbackr/Frontend/node_modules/glob-stream/index.js:80:17
    at Array.map (native)
    at Object.gs.create (/home/karl/Work/cnc/feedbackr/Frontend/node_modules/glob-stream/index.js:79:29)
    at Gulp.src (/home/karl/Work/cnc/feedbackr/Frontend/node_modules/vinyl-fs/lib/src/index.js:33:23)
    at module.exports (build.js.dev.ts:13:22)
    at Gulp.<anonymous> (tasks_tools.ts:24:31)
[12:20:57] 'serve.dev' errored after 11 s
[12:20:57] TypeError in plugin 'run-sequence(build.js.dev)'
```

I compared the installed node modules of a working version and the version which does not work any more (left is the working version)

```
19c19
< │ ├── caniuse-db@1.0.30000524
---
> │ ├── caniuse-db@1.0.30000525
182c182
< │ │ └─┬ reduce-css-calc@1.2.4
---
> │ │ └─┬ reduce-css-calc@1.2.5
183a184
> │ │   ├── math-expression-evaluator@1.2.9
369c370
< │ ├─┬ readable-stream@2.1.4
---
> │ ├─┬ readable-stream@2.1.5
536c537
< │ ├── graceful-fs@4.1.5
---
> │ ├── graceful-fs@4.1.6
660c661
< ├── jasmine-spec-reporter@2.5.0
---
> ├── jasmine-spec-reporter@2.7.0
703c704
< │ ├─┬ istanbul@0.4.4
---
> │ ├─┬ istanbul@0.4.5
717,719c718
< │ │ ├─┬ fileset@0.2.1
< │ │ │ ├── glob@5.0.15
< │ │ │ └── minimatch@2.0.10
---
> │ │ ├── glob@5.0.15
722c721
< │ │ │ └─┬ uglify-js@2.7.2
---
> │ │ │ └─┬ uglify-js@2.7.3
852a852,854
> │ │ ├─┬ fileset@0.2.1
> │ │ │ ├── glob@5.0.15
> │ │ │ └── minimatch@2.0.10
855c857
< │ │ │ └─┬ uglify-js@2.7.2
---
> │ │ │ └─┬ uglify-js@2.7.3
981c983
< ├─┬ systemjs-builder@0.15.26
---
> ├─┬ systemjs-builder@0.15.28
1009a1012,1013
> │ ├─┬ babel-plugin-transform-cjs-system-wrapper@0.0.3
> │ │ └── babel-plugin-transform-cjs-system-require@0.0.2
1025c1029
< │ ├── systemjs@0.19.36
---
> │ ├── systemjs@0.19.37
1032c1036
< │ └─┬ uglify-js@2.7.2
---
> │ └─┬ uglify-js@2.7.3
1090c1094
< │ ├─┬ typings-core@1.4.0
---
> │ ├─┬ typings-core@1.4.1
1097c1101
< │ │ │ └─┬ write-file-atomic@1.1.4
---
```

The strange thing is that it works as expected when i remove cssnano ...:
```
if (isProd) {
  // processors.push(
  //   cssnano({
  //     discardComments: {removeAll: true}
  //   })
  // );
}
```

The very strange fact is, that isProd is false. 

Any ideas?

**Comment by chinmoymohanty85** [comment]
I'm facing the same issue.. for me  the error is in 
TypeError in plugin 'run-sequence(build.html_css)'

@karlhaas -> unfortunately your workaround doesn't work for me.

I've tried changing version of run-sequence plugin to a few previous releases, but to no avail.

**Comment by kfichter** [comment]
Facing the same issue and can confirm that removing 
`if (isProd) {
  processors.push(
    cssnano({
      discardComments: {removeAll: true},
      discardUnused: false, // unsafe, see http://goo.gl/RtrzwF
      zindex: false, // unsafe, see http://goo.gl/vZ4gbQ
      reduceIdents: false // unsafe, see http://goo.gl/tNOPv0
    })
  );
}`

fixes this issue

**Comment by totev** [comment]
I can confirm this behaviour and the temporary fix. 

@kfichter how the hell did you come up with this fix?

**Comment by kfichter** [comment]
@totev: not me, @htdt from [here](https://github.com/mgechev/angular2-seed/issues/1235)

**Comment by mgechev** [comment]
Seems related to https://github.com/mgechev/angular2-seed/issues/1235. Most likely it's related to a problem in cssnano. It'll be interesting to share the CSS which cases the issue and try to reproduce it.
