### ISSUE TITLE
Error While npm run build.prod

### ISSUE THREAD

**Issue by Lastik** [mgechev/angular2-seed#1263]
Hello,

I am possibly facing the same issue as https://github.com/mgechev/angular2-seed/issues/1217.

Also only when I am running build.prod. The output is quite the same. Using clean build. Tried cloning master branch taking build from the site.

```
/Users/DmitryGr/Downloads/alfabank-proj/client/node_modules/stylelint/dist/utils/configurationError.js:8
  var err = new Error(text);
            ^
Error: No configuration found
    at exports.default (/Users/DmitryGr/Downloads/alfabank-proj/client/node_modules/stylelint/dist/utils/configurationError.js:8:13)
    at /Users/DmitryGr/Downloads/alfabank-proj/client/node_modules/stylelint/dist/buildConfig.js:43:54

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "build.prod"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 build.prod: `gulp build.prod --color --config-env prod`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-seed@0.0.0 build.prod script 'gulp build.prod --color --config-env prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build.prod --color --config-env prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/DmitryGr/Downloads/alfabank-proj/client/npm-debug.log
```

**Comment by Lastik** [comment]
Sorry for opening the issue. After taking sources and building from scratch, everything is ok.
