### ISSUE TITLE
Confused on build.tools

### ISSUE THREAD

**Issue by TianCNCA** [mgechev/angular2-seed#1264]
So the build.tools task first deletes all the .js files from the tools folder and then try to rebuild them by running the build.js.tools task.

Sometimes it ran successfully and I don't understand how since all js files were deleted. Sometimes it fails with an error
```
[12:56:51] Error: Cannot find module 'C:\Working\EverestGIT\Src\Everest.SPA\tools\tasks\seed\build.js.tools'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Gulp.<anonymous> (C:\Working\EverestGIT\Src\Everest.SPA\tools\utils\seed\tasks_tools.js:17:20)
    at module.exports (C:\Working\EverestGIT\Src\Everest.SPA\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Working\EverestGIT\Src\Everest.SPA\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Working\EverestGIT\Src\Everest.SPA\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Working\EverestGIT\Src\Everest.SPA\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at runNextSet (C:\Working\EverestGIT\Src\Everest.SPA\node_modules\run-sequence\index.js:86:16)
```
which is understandable as the ts file hasn't been compiled yet. So can someone please explain to me how does this task work and how do I fix it?

**Comment by TianCNCA** [comment]
#902 fixed my problem.
