### ISSUE TITLE
compile.ahead.prod not working with MomentModule

### ISSUE THREAD

**Issue by tinuF** [mgechev/angular2-seed#1289]
I'm trying to catch up with ahead of time compilation: https://github.com/tinuF/eTuneBook2.

npm start works fine. npm run serve.prod throws an error:

[22:33:57] Starting 'compile.ahead.prod'...
Error: Unexpected value 'MomentModule' imported by the module 'TunePlayedModule'
    at /Users/bxplr/dev/eTuneBook2/node_modules/@angular/compiler/bundles/compiler.umd.js:14118:37
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/bxplr/dev/eTuneBook2/node_modules/@angular/compiler/bundles/compiler.umd.js:14103:46)
    at /Users/bxplr/dev/eTuneBook2/node_modules/@angular/compiler/bundles/compiler.umd.js:12947:58
    at Array.forEach (native)
    at OfflineCompiler.analyzeModules (/Users/bxplr/dev/eTuneBook2/node_modules/@angular/compiler/bundles/compiler.umd.js:12946:21)
    at CodeGenerator.codegen (/Users/iminar/Dev/angular/modules/@angular/compiler-cli/src/codegen.ts:110:45)
    at codegen (/Users/bxplr/dev/eTuneBook2/tools/tasks/seed/compile.ahead.prod.ts:14:69)
    at Object.main (/Users/bxplr/dev/tools/@angular/tsc-wrapped/src/main.ts:44:12)
    at module.exports (/Users/bxplr/dev/eTuneBook2/tools/tasks/seed/compile.ahead.prod.ts:34:7)
Compilation failed

**Comment by mgechev** [comment]
Are you distributing MomentModule with metadata produced by `ngc`? For reference, you can take a look at [this PR](https://github.com/angular/mobile-toolkit/pull/99).

**Comment by mgechev** [comment]
Fixed by https://github.com/mgechev/angular2-seed/commit/bdf9cbf2cbee72ca3ba862c4b2863fef0e31b4ad.
