### ISSUE TITLE
Cannot find module 'rxjs/bundles/Rx.js'

### ISSUE THREAD

**Issue by rousdan** [mgechev/angular2-seed#1298]
I'm having this issue and i'm not sure why it is happening in the build.html_css task i don't know if the problems its cuz i have some external dependencies that are using the old rxjs version so i'll  leave my package.json as well 
```
[13:13:07] 'build.html_css' errored after 32 s
[13:13:07] Error: Cannot find module 'rxjs/bundles/Rx.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.require.resolve (internal/module.js:16:19)
    at /Users/Dan/development/manager/tools/config/seed.config.js:204:56
    at Array.forEach (native)
    at normalizeDependencies (/Users/Dan/development/manager/tools/config/seed.config.js:204:10)
    at ProjectConfig.Object.defineProperty.get [as DEPENDENCIES] (/Users/Dan/development/manager/tools/config/seed.config.js:179:20)
    at getExternalCss (/Users/Dan/development/manager/tools/tasks/seed/build.html_css.js:67:20)
    at getExternalCssStream (/Users/Dan/development/manager/tools/tasks/seed/build.html_css.js:63:21)
    at processAllExternalStylesheets (/Users/Dan/development/manager/tools/tasks/seed/build.html_css.js:56:18)
    at processExternalStylesheets (/Users/Dan/development/manager/tools/tasks/seed/build.html_css.js:53:35)
[13:13:07] 'serve.dev' errored after 1.27 min
[13:13:07] Error in plugin 'run-sequence(build.html_css)'
Message:
    Cannot find module 'rxjs/bundles/Rx.js'
Details:
    code: MODULE_NOT_FOUND
Stack:
Error: Cannot find module 'rxjs/bundles/Rx.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.require.resolve (internal/module.js:16:19)
    at /Users/Dan/development/manager/tools/config/seed.config.js:204:56
    at Array.forEach (native)
    at normalizeDependencies (/Users/Dan/development/manager/tools/config/seed.config.js:204:10)
    at ProjectConfig.Object.defineProperty.get [as DEPENDENCIES] (/Users/Dan/development/manager/tools/config/seed.config.js:179:20)
    at getExternalCss (/Users/Dan/development/manager/tools/tasks/seed/build.html_css.js:67:20)
    at getExternalCssStream (/Users/Dan/development/manager/tools/tasks/seed/build.html_css.js:63:21)
    at processAllExternalStylesheets (/Users/Dan/development/manager/tools/tasks/seed/build.html_css.js:56:18)
    at processExternalStylesheets (/Users/Dan/development/manager/tools/tasks/seed/build.html_css.js:53:35)
[13:13:07] 'build.dev' errored after 1.27 min
[13:13:07] Error in plugin 'run-sequence(serve.dev)'
Message:
    Cannot find module 'rxjs/bundles/Rx.js'
Details:
    code: MODULE_NOT_FOUND
Stack:
Error: Cannot find module 'rxjs/bundles/Rx.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.require.resolve (internal/module.js:16:19)
    at /Users/Dan/development/manager/tools/config/seed.config.js:204:56
    at Array.forEach (native)
    at normalizeDependencies (/Users/Dan/development/manager/tools/config/seed.config.js:204:10)
    at ProjectConfig.Object.defineProperty.get [as DEPENDENCIES] (/Users/Dan/development/manager/tools/config/seed.config.js:179:20)
    at getExternalCss (/Users/Dan/development/manager/tools/tasks/seed/build.html_css.js:67:20)
    at getExternalCssStream (/Users/Dan/development/manager/tools/tasks/seed/build.html_css.js:63:21)
    at processAllExternalStylesheets (/Users/Dan/development/manager/tools/tasks/seed/build.html_css.js:56:18)
    at processExternalStylesheets (/Users/Dan/development/manager/tools/tasks/seed/build.html_css.js:53:35)
[13:13:07] 'build.dev' errored after 1.27 min
[13:13:07] Error in plugin 'run-sequence(build.html_css)'
Message:
    Cannot find module 'rxjs/bundles/Rx.js'
Details:
    code: MODULE_NOT_FOUND
Stack:
Error: Cannot find module 'rxjs/bundles/Rx.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.require.resolve (internal/module.js:16:19)
    at /Users/Dan/development/manager/tools/config/seed.config.js:204:56
    at Array.forEach (native)
    at normalizeDependencies (/Users/Dan/development/manager/tools/config/seed.config.js:204:10)
    at ProjectConfig.Object.defineProperty.get [as DEPENDENCIES] (/Users/Dan/development/manager/tools/config/seed.config.js:179:20)
    at getExternalCss
```

`package.json`
```
"devDependencies": {
    "@angular/compiler-cli": "^0.6.0",
    "@angular/platform-server": "^2.0.0-rc.6",
    "@angular/tsc-wrapped": "^0.3.0",
    "@mean-expert/loopback-sdk-builder": "^2.0.2",
    "async": "^2.0.0",
    "autoprefixer": "^6.3.7",
    "browser-sync": "^2.13.0",
    "codelyzer": "0.0.25",
    "colorguard": "^1.2.0",
    "compression": "^1.6.2",
    "connect": "^3.4.1",
    "connect-history-api-fallback": "^1.2.0",
    "connect-livereload": "^0.5.4",
    "cssnano": "^3.7.3",
    "deep-extend": "^0.4.1",
    "doiuse": "^2.4.1",
    "event-stream": "^3.3.3",
    "express": "~4.14.0",
    "express-history-api-fallback": "^2.0.0",
    "extend": "^3.0.0",
    "gulp": "^3.9.1",
    "gulp-cached": "^1.1.0",
    "gulp-clean-css": "^2.0.11",
    "gulp-concat": "^2.6.0",
    "gulp-concat-css": "^2.3.0",
    "gulp-filter": "^4.0.0",
    "gulp-inject": "^4.1.0",
    "gulp-inline-ng2-template": "^3.0.1",
    "gulp-load-plugins": "^1.2.4",
    "gulp-plumber": "~1.1.0",
    "gulp-postcss": "^6.1.1",
    "gulp-progeny": "^0.3.1",
    "gulp-protractor": "^2.4.0",
    "gulp-replace": "^0.5.4",
    "gulp-sass": "^2.3.2",
    "gulp-sass-lint": "^1.2.0",
    "gulp-sourcemaps": "2.0.0-alpha",
    "gulp-template": "^4.0.0",
    "gulp-tslint": "^6.0.1",
    "gulp-typescript": "~2.13.6",
    "gulp-uglify": "^2.0.0",
    "gulp-util": "^3.0.7",
    "gulp-watch": "^4.3.8",
    "is-ci": "^1.0.9",
    "isstream": "^0.1.2",
    "jasmine-core": "~2.4.1",
    "jasmine-spec-reporter": "^2.5.0",
    "karma": "~0.13.22",
    "karma-chrome-launcher": "~1.0.1",
    "karma-coverage": "^1.1.0",
    "karma-jasmine": "~1.0.2",
    "karma-mocha-reporter": "^2.0.4",
    "merge-stream": "^1.0.0",
    "open": "0.0.5",
    "postcss-reporter": "^1.4.1",
    "protractor": "^3.3.0",
    "remap-istanbul": "^0.6.4",
    "rimraf": "^2.5.3",
    "run-sequence": "^1.2.2",
    "semver": "^5.3.0",
    "serve-static": "^1.11.1",
    "slash": "~1.0.0",
    "stream-series": "^0.1.1",
    "stylelint": "^7.0.2",
    "stylelint-config-standard": "^11.0.0",
    "systemjs-builder": "0.15.14",
    "tildify": "^1.2.0",
    "tiny-lr": "^0.2.1",
    "traceur": "^0.0.111",
    "ts-node": "^1.0.0",
    "tslint": "^3.13.0",
    "tslint-stylish": "2.1.0-beta",
    "typescript": "^2.0.2",
    "vinyl-buffer": "^1.0.0",
    "vinyl-source-stream": "^1.1.0",
    "walk": "^2.3.9",
    "yargs": "^4.8.0"
  },
  "dependencies": {
    "@angular/common": "2.0.0-rc.6",
    "@angular/compiler": "2.0.0-rc.6",
    "@angular/core": "2.0.0-rc.6",
    "@angular/forms": "2.0.0-rc.6",
    "@angular/http": "2.0.0-rc.6",
    "@angular/platform-browser": "2.0.0-rc.6",
    "@angular/platform-browser-dynamic": "2.0.0-rc.6",
    "@angular/router": "3.0.0-rc.2",
    "angular2-modal": "^2.0.0-beta.12",
    "angular2-toaster": "^0.5.0-rc.6",
    "animate.css": "^3.5.1",
    "bootstrap": "^3.3.6",
    "core-js": "^2.4.0",
    "es6-module-loader": "^0.17.8",
    "font-awesome": "^4.6.1",
    "jquery": "^2.2.3",
    "lodash": "^4.13.1",
    "metismenu": "^2.5.2",
    "moment": "^2.14.1",
    "reflect-metadata": "^0.1.8",
    "rxjs": "5.0.0-beta.11",
    "socket.io": "^1.4.8",
    "socket.io-client": "^1.4.8",
    "systemjs": "0.19.27",
    "typings": "^1.3.1",
    "underscore": "^1.8.3",
    "zone.js": "0.6.17"
  }
```
i think maybe its because this deps   "angular2-modal": "^2.0.0-beta.12", "angular2-toaster": "^0.5.0-rc.6",

**Comment by rousdan** [comment]
nvm i found the issue i did't delete the `dist` folder  closing this

**Comment by rousdan** [comment]
I having this issue only when i do `npm start`  but when i do `npm run build.prod` is not happening or `serve.prod`

**Comment by jovermier** [comment]
Try running npm postinstall
