### ISSUE TITLE
Error after upgrading angular to rc.6

### ISSUE THREAD

**Issue by karlhaas** [mgechev/angular2-seed#1311]
After upgrading to angular rc.6 I get the following error when loading the app:

```
Error: (SystemJS) Unexpected token <
	SyntaxError: Unexpected token <
	    at Object.eval (http://localhost:5555/app/main.js:2:14)
	    at eval (http://localhost:5555/app/main.js:12:4)
	    at eval (http://localhost:5555/app/main.js:13:3)
	Evaluating http://localhost:5555/node_modules/rxjs/Subject
	Evaluating http://localhost:5555/app/main.js
	Error loading http://localhost:5555/app/main.js
	    at Object.eval (http://localhost:5555/app/main.js:2:14)
	    at eval (http://localhost:5555/app/main.js:12:4)
	    at eval (http://localhost:5555/app/main.js:13:3)
	Evaluating http://localhost:5555/node_modules/rxjs/Subject
	Evaluating http://localhost:5555/app/main.js
	Error loading http://localhost:5555/app/main.js "Report this error at https://github.com/mgechev/angular2-seed/issues"
```

Any ideas what could be wrong?

**Comment by karlhaas** [comment]
The app loads without errors in prod mode

**Comment by karlhaas** [comment]
fixed rxjs system js config

**Comment by uelton-hbsis** [comment]
Hey @karlhaas, 
I have the same issue, can u share your solution, please?
Thanks
