### ISSUE TITLE
Gulp Typescript requires node modules

### ISSUE THREAD

**Issue by jerryorta-dev** [mgechev/angular2-seed#132]
After the gulp refactor to typescript, Terminal ( command line ) throws the following error when running gulp commands:

[03:08:39] Requiring external module ts-node/register
⨯ Unable to compile TypeScript

Installing ts-node and typescript-node fixes the issue.

I would have submitted a pull request, but not sure whether this is something that needs to be document for the developer to install globally:

	```
		nom install ts-node -g
		npm install typescript-node -g
	```

Or locally:

	``` 
		nom install ts-node --save-dev
		npm install typescript-node --save-dev
	```

 I personally have to work with many repositories, so I install everything locally, and prefer as flat install as possible. But this is subjective to each developer's workflow. In this case, I would install all these separately:

	```
		npm install ts-node —save-dev
		npm install typescript-node —save-dev
		npm install typescript-register —save-dev
		npm install typescript-require —save-dev
	```

**Comment by ludohenin** [comment]
`ts-node` is defined in `package.son` so should work.
Have you run `npm install` ?

**Comment by jerryorta-dev** [comment]
yes. I have to run npm install twice, because ts-node is not loaded immediately after it's installed the first time. I test by deleting the node_modules folder and running npm install again.

**Comment by ludohenin** [comment]
Strange, I just did exactly the same thing and it works fine.
* OSX 10.11
* node 4.1.1
* npm 3.3.5

**Comment by ludohenin** [comment]
Anyone else having the same issue ?

// cc: @mgechev @NathanWalker

**Comment by jerryorta-dev** [comment]
This may very well be unique to my environment. Sorry for the trouble if that is so.

Among my work and private projects, the app environments are vastly different, so I do not install anything globally. 

For example I've set up my .bash_profile with this snippet:

```
alias npm-local='PATH=$(npm bin):$PATH'
```

Which allows me to run npm modules only designed to run globally - locally. I would then run tsd like this:

```$ npm-local tsd install```

Then in my fork of this project, I have to do this for the gulp post install scripts:

```javascript

  // --------------
  // Post install
  gulp.task('install.typings', ['clean.tsd_typings'], shell.task([
    'node_modules/tsd/build/cli.js reinstall --overwrite',
    'node_modules/tsd/build/cli.js link',
    'node_modules/tsd/build/cli.js rebundle'
  ]));

```
It's a little bit of a pain, but keeps my projects from colliding.

**Comment by mgechev** [comment]
Hey @jerryorta-dev I can't experience that issue either.

Would you try to reproduce it with the latest changes in the repo? Thanks for reporting it!

**Comment by jerryorta-dev** [comment]
My specs:
- OSX 10.10.5
- node: 4.1.1
- npm: 3.3.6


To reproduce:
- pulled from latest master
- run npm cache clean
- remove node_modules
- remove tsd_typings
- npm install

Received the following error:

```bash
Jerrys-MacBook-Pro:angular2-seed jerryorta-dev$ gulp serve.dev
[04:17:14] Failed to load external module typescript-node/register
[04:17:14] Failed to load external module typescript-register
[04:17:14] Failed to load external module typescript-require
/Users/jerryorta-dev/Dev/UIUXEngineering/angular2-seed/gulpfile.ts:2
import * as gulp from 'gulp';
^^^^^^

SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:413:25)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
Jerrys-MacBook-Pro:angular2-seed jerryorta-dev$ 
```

**Comment by NathanWalker** [comment]
I have not experienced this issue on a clean setup.

**Comment by jerryorta-dev** [comment]
I'd close this until it becomes an issue for anyone else then. I'll investigate my set up again... re-clone the repo again, etc.

**Comment by mgechev** [comment]
Okay, thanks for that. If you encounter it again let us know.

**Comment by jesperronn** [comment]
Also a problem for me. If I run any `gulp` command directly it fails. Example

```
$ gulp build.dev
[23:32:48] Failed to load external module typescript-node/register
[23:32:48] Requiring external module typescript-register
/Users/jesper/src/angular2-seed/node_modules/typescript-register/index.js:132
    var result = checker.emitFiles();
                         ^

TypeError: checker.emitFiles is not a function
    at compile (/Users/jesper/src/angular2-seed/node_modules/typescript-register/index.js:132:26)
    at Object.req (/Users/jesper/src/angular2-seed/node_modules/typescript-register/index.js:29:9)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp-cli/index.js:120:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/local/lib/node_modules/gulp-cli/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:185:9)
```

However, `npm run build.dev` works just fine as expected.

My globally installed modules:

```
$ npm -g --depth 0 ls
/Users/jesper/.nvm/versions/node/v4.1.2/lib
├── bower@1.6.3
├── git-travis@1.0.2
├── grunt-cli@0.1.13
├── gulp-cli@0.3.0
├── karma-cli@0.1.1
├── npm@2.14.7
├── npm-check@4.1.2
└── phantomas@1.12.0
```

So, as @jerryorta-dev reports: None of the listed modules installed globally.

Note, however, that specifically using the locally installed Gulp works:

```
$ $(npm bin)/gulp build.dev

[23:35:14] Requiring external module ts-node/register
[23:35:17] Using gulpfile ~/src/angular2-seed/gulpfile.ts
[23:35:17] Starting 'build.dev'...
[23:35:17] Starting 'clean.dist'...
[23:35:17] Finished 'clean.dist' after 13 ms
[23:35:17] Starting 'tslint'...
[23:35:18] Finished 'tslint' after 934 ms
[23:35:18] Starting 'build.jslib.dev'...
[23:35:18] Finished 'build.jslib.dev' after 40 ms
[23:35:18] Starting 'build.sass.dev'...
[23:35:18] Finished 'build.sass.dev' after 35 ms
[23:35:18] Starting 'build.js.dev'...
[23:35:20] Finished 'build.js.dev' after 1.61 s
[23:35:20] Starting 'build.csslib.dev'...
[23:35:20] Finished 'build.csslib.dev' after 6.05 ms
[23:35:20] Starting 'build.fonts'...
[23:35:20] Finished 'build.fonts' after 7.43 ms
[23:35:20] Starting 'build.index.dev'...
[23:35:20] gulp-inject 8 files into index.html.
[23:35:20] Finished 'build.index.dev' after 31 ms
[23:35:20] Finished 'build.dev' after 2.68 s
```

Is this another problem, or the same as @jerryorta-dev described??

**Comment by kamikaze** [comment]
+1

**Comment by talmog** [comment]
+1

**Comment by mgechev** [comment]
You can run:

```bash
gulp build.dev
```

You can get the following two errors:

```
[12:08:04] Failed to load external module ts-node/register
[12:08:04] Failed to load external module typescript-node/register
[12:08:04] Failed to load external module typescript-register
[12:08:04] Failed to load external module typescript-require
/Users/mgechev/Projects/angular2-seed/gulpfile.ts:1
(function (exports, require, module, __filename, __dirname) { import * as gulp from 'gulp';
```

or 

```
[12:08:23] Failed to load external module ts-node/register
[12:08:23] Failed to load external module typescript-node/register
[12:08:23] Requiring external module typescript-register
/Users/mgechev/Projects/angular2-seed/node_modules/typescript-register/index.js:132
    var result = checker.emitFiles();
                         ^
```

Just run:

```bash
npm install typescript-register ts-node
```

**Comment by sachingk** [comment]
I am facing the same issue here. How to resolve it ?

**Comment by mgechev** [comment]
Take a look at my comment above.

**Comment by stefanocke** [comment]
@mgechev 
As far as I understand, typescript-register has been deprecated in favor of ts-node. See https://github.com/pspeter3/typescript-register/blob/master/README.md. Why do we need to install both?  I thin the checker.emitFiles error comes from typescript-register. Why not just removing it completely from package.json? Is it required by something else?
I removed it, and the gulp build seems to work so far...

**Comment by mgechev** [comment]
@stefanocke yep, just removed it.

**Comment by e-oz** [comment]
Second time I have to work with people to help them install all things, it takes a lot of time.
Please consider to enlist all global dependencies or ensure `npm install` works same everywhere.

**Comment by NathanWalker** [comment]
@e-oz Agreed. I'm trying to make this more reliable and stable here: https://github.com/mgechev/angular2-seed/pull/411
Still working through it, but hopefully soon. `typings` is much better than `tsd`, and while I'm at it, I'm trying to make `npm install` just works without hassle.

**Comment by mgechev** [comment]
@NathanWalker I'm following the progress. Switching to typings looks like a good idea to me. Until the refactoring is ready I updated the [readme with more instructions](https://github.com/mgechev/angular2-seed/commit/a2fa0fe99302f178382a2424b8196ff3839a5942).

**Comment by e-oz** [comment]
I just finished one problem-solving session and can say all issues were because node was installed with sudo (as default installer does).

**Comment by NathanWalker** [comment]
Ah yes, I have seen that trouble on other dev setups. Definitely can be frustrating when trying to get a team setup.

**Comment by loul42** [comment]
npm install typescript-register ts-node 
doesn't fix the      

var result = checker.emitFiles(); error for me.

**Comment by eng-almeida** [comment]
@loul42 +1

**Comment by loul42** [comment]
@eng-almeida Are you using Atom as IDE ?

Close it  & npm start, it will solve your issue...

**Comment by eng-almeida** [comment]
No, I'm using WebStorm. npm start will work but gulp commands like, gulp serve --env dev, should also work.

**Comment by e-oz** [comment]
@eng-almeida if you are on osx/linux, try to reinstall node and npm, using one of these techniques: https://gist.github.com/e-oz/32182190f731ced284ea

**Comment by TsarS** [comment]
@loul42 Wow. It works for me. But it's very strange

**Comment by ashkank83** [comment]
I'm getting this exact same error with the latest version of the seed. Is there any solutions? Node v 4.4.4 and npm -3.8.9

**Comment by shershen08** [comment]
Nodejs 6.0.0, tsc 1.8.10, NPM 3.8.6, MacOS 10.11

I Have the same issue if I add 
```     "files":[
    "./typings/browser.d.ts",
    "./typings/index.d.ts"
  ]```

to typings.json
Without it it looks like:
```
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "declaration": false,
        "noImplicitAny": false,
        "removeComments": true,
        "noLib": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "sourceMap": true
    },
    "exclude": [
        "node_modules"
    ],
    "compileOnSave": false
}
```
without it if fails with even more errors:

**$ npm run serve.dev**
```
> angular2-sample-app@0.0.0 serve.dev /Users/myuserfolder_/_Other/angular-2-ts/angular2-sample-app
> gulp serve --env dev

[23:18:31] Requiring external module ts-node/register
(node:30668) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[23:18:33] Loading task clean all
[23:18:33] Loading task clean dist
[23:18:33] Loading task clean test
[23:18:33] Loading task clean tmp
[23:18:33] Loading task check.versions
[23:18:34] Using gulpfile ~/_Other/angular-2-ts/angular2-sample-app/gulpfile.ts
[23:18:34] Starting 'serve'...
[23:18:34] Loading task server.start
[23:18:34] Loading task watch.serve
[23:18:34] Starting 'build.dev'...
[23:18:34] Loading task tslint
[23:18:35] Loading task build.sass.dev
[23:18:35] Loading task build.img.dev
[23:18:35] Loading task build.js.dev
(node:30668) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[23:18:36] Loading task build.index
[23:18:36] Starting 'clean.dist'...
[23:18:36] Finished 'clean.dist' after 14 ms
[23:18:36] Starting 'tslint'...
[23:18:38] Finished 'tslint' after 1.25 s
[23:18:38] Starting 'build.sass.dev'...
[23:18:38] Finished 'build.sass.dev' after 22 ms
[23:18:38] Starting 'build.img.dev'...
[23:18:38] Finished 'build.img.dev' after 6.88 ms
[23:18:38] Starting 'build.js.dev'...
(node:30668) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
/Users/myuserfolder_/_Other/angular-2-ts/angular2-sample-app/node_modules/angularfire2/angularfire2.d.ts(1,26): error TS2307: Cannot find module '@angular/core'.
/Users/myuserfolder_/_Other/angular-2-ts/angular2-sample-app/node_modules/angularfire2/database/database.d.ts(8,29): error TS2304: Cannot find name 'Firebase'.
/Users/myuserfolder_/_Other/angular-2-ts/angular2-sample-app/node_modules/angularfire2/database/database.d.ts(9,31): error TS2304: Cannot find name 'Firebase'.
```

**Comment by irsick** [comment]
I had this error
```
Requiring external module ts-node/register
Error: EACCES: permission denied, mkdir '/tmp/ts-node/195a009122f3b9b95d959ac08325ce21985c73bd'
```
The issue was that for for multi-developer environment the script creates **ts-node** folder in /tmp for first user. Other users obviously have no permission to write there.

The solution was
`chmod -r 777 /tmp/ts-node`

**Comment by mikemichaelis** [comment]
I can build locally just fine.  I'm now trying to build using Visual Studio Online and receiving these same errors as in the OP.  The error I'm receiving is posted below, it's clear the gulpfile.ts is being directly executed.  How does gulpfile.ts get compiled into gulpfile.js?  Or does it?  None of the global installs suggested above are installed on my local dev box yet I compile just fine.  Please help :-)

2016-10-26T15:18:09.4619665Z > gulp build.prod --color --config-env prod
2016-10-26T15:18:09.4619665Z 
2016-10-26T15:18:10.7403428Z [[90m15:18:10[39m] [31mFailed to load external module[39m [35mts-node/register[39m
2016-10-26T15:18:10.7403428Z [[90m15:18:10[39m] [31mFailed to load external module[39m [35mtypescript-node/register[39m
2016-10-26T15:18:10.7403428Z [[90m15:18:10[39m] [31mFailed to load external module[39m [35mtypescript-register[39m
2016-10-26T15:18:10.7403428Z [[90m15:18:10[39m] [31mFailed to load external module[39m [35mtypescript-require[39m
2016-10-26T15:18:10.7484439Z C:\a\1\s\**gulpfile.ts:1**
2016-10-26T15:18:10.7484439Z (function (exports, require, module, __filename, __dirname) { import * as gulp from 'gulp';
2016-10-26T15:18:10.7484439Z                                                               ^^^^^^
2016-10-26T15:18:10.7484439Z 
2016-10-26T15:18:10.7484439Z SyntaxError: Unexpected token **import**

**Comment by denissb** [comment]
@loul42 - struggling with the same thing

**Comment by maxpaj** [comment]
I saw this error when I had Node v4.6 something installed when I started the installation. I had some error while installing so I switched to Node v7 something (Node v6+ is required) and then continued the installation. This is when the error appeared.

The solution was to delete the entire folder, cloned and restarted the installation process and it went fine.
