### ISSUE TITLE
Build command doesn't accept ENV params

### ISSUE THREAD

**Issue by irsick** [mgechev/angular2-seed#1324]
**IMPORTANT**: This repository's issues are reserved for feature requests and bug reports. Do not submit support requests here.

**Steps to reproduce and a minimal demo of the problem**
Based on solution found [here](https://github.com/mgechev/angular2-seed/issues/1218)

Created a file tools/env/staging.ts.
Ran the seed with npm run build.prod -- --config-env staging.

**Current behavior**

```
[16:19:06] 'build.prod' errored after 15 s
[16:19:06] TypeError in plugin 'run-sequence(build.js.prod)'
Message:
    Path must be a string. Received [ 'prod', 'staging' ]
Stack:
TypeError: Path must be a string. Received [ 'prod', 'staging' ]
    at assertPath (path.js:7:11)
    at Object.join (path.js:1213:7)
    at getConfig (/var/www/sites_CLIENT_ri/tools/utils/seed/template_locals.ts:8:22)
    at Object.templateLocals (/var/www/sites_CLIENT_ri/tools/utils/seed/template_locals.ts:28:18)
    at module.exports (/var/www/sites_CLIENT_ri/tools/tasks/seed/build.js.prod.ts:38:28)
    at Gulp.<anonymous> (/var/www/sites_CLIENT_ri/tools/utils/seed/tasks_tools.ts:32:31)
    at module.exports (/var/www/sites_CLIENT_ri/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/var/www/sites_CLIENT_ri/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/var/www/sites_CLIENT_ri/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/var/www/sites_CLIENT_ri/node_modules/orchestrator/index.js:134:8)
```

**Expected/desired behavior**

Production build with staging environment settings

**Other information**

Same behavior if I run
`npm run build.prod -- --config-env dev`
or even
`npm run build.prod -- --config-env prod`

Node 6.5.0
OS Cent OS 7

**Comment by mgechev** [comment]
This is by design. In `build.prod` script we explicitly set that we want the `prod` environment to be used. What you can do is either:

- Modify `build.prod` task in `package.json` to not set the `--config-env` parameter and invoke the production build like you do: `npm run build.prod -- --config-env prod`.
- Add entry in the `scripts` section in `package.json`: `"build.staging": gulp build.prod --color --config-env staging"`.

**Comment by irsick** [comment]
Thanks for quick response. This works perfectly!

I think it would be great idea to add 'How to add new config environment' wiki article. Staging was mentioned several times all over the docs, but I couldn't find complete example.
