### ISSUE TITLE
Add PhantomJS2 to Karma's browsers

### ISSUE THREAD

**Issue by ryzy** [mgechev/angular2-seed#137]

**Comment by ryzy** [comment]
I'm trying to come up with working code for that, but have a problem with PhantomJS 2.0 throwing some weird errors.

Here are the changes: https://github.com/ryzy/angular2-seed/commit/4d14f5f07825274043003439a3428a8760792f74

When I run it, I have following result:
```
[20:26:28] Starting 'karma.start'...
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS2
INFO [launcher]: Starting browser Chrome
INFO [PhantomJS 2.0.0 (Mac OS X 0.0.0)]: Connected on socket fN-19W3eEMiVRol7N_p8 with id 74726523
PhantomJS 2.0.0 (Mac OS X 0.0.0) ERROR: 'TypeError: undefined is not a constructor (evaluating 'new exports.Map()')
	Evaluating http://localhost:9876/base/node_modules/angular2/src/core/facade/collection.js
	Evaluating http://localhost:9876/base/node_modules/angular2/src/core/dom/browser_adapter.js
	Error loading http://localhost:9876/base/node_modules/angular2/src/core/dom/browser_adapter.js'

PhantomJS 2.0.0 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.001 secs / 0 secs)
PhantomJS 2.0.0 (Mac OS X 0.0.0): Executed 0 of 0 ERROR (0.001 secs / 0 secs)
Chrome 45.0.2454 (Mac OS X 10.11.1): Executed 3 of 3 SUCCESS (0.083 secs / 0.079 secs)
[20:26:31] 'karma.start' errored after 2.52 s
```

Any ideas what might be wrong? Still quite new with ES6/TS/Angular2.

**Comment by tarlepp** [comment]
Yeah, I tried that too but I got some referenceErrors about missing 'require'. Going to try this one again...

**Comment by ryzy** [comment]
@tarlepp there were some missing references and even without PhantomJS there were warning. I fixed it in that change: https://github.com/ryzy/angular2-seed/commit/c21c7cdb9804219f8829c376574a79859a4ce391

Will do PR with these two commits once I managed to make PhantomJS work...

**Comment by tarlepp** [comment]
With just installing ```karma-phantomjs2-launcher``` and changing the ```karma.conf.js``` I got following.

```bash
wunder@wunder-VirtualBox:~/projects/angular2-seed$ npm test

> angular2-seed@0.0.0 test /home/wunder/projects/angular2-seed
> gulp test

[22:34:14] Requiring external module ts-node/register
[22:34:17] Using gulpfile ~/projects/angular2-seed/gulpfile.ts
[22:34:17] Starting 'build.test'...
[22:34:20] Finished 'build.test' after 3.43 s
[22:34:20] Starting 'karma.start'...
WARN [watcher]: Pattern "/home/wunder/projects/angular2-seed/node_modules/zone.js/dist/zone-microtask.js" does not match any file.
WARN [watcher]: Pattern "/home/wunder/projects/angular2-seed/node_modules/zone.js/dist/long-stack-trace-zone.js" does not match any file.
WARN [watcher]: Pattern "/home/wunder/projects/angular2-seed/node_modules/zone.js/dist/jasmine-patch.js" does not match any file.
WARN [watcher]: Pattern "/home/wunder/projects/angular2-seed/node_modules/@reactivex/rxjs/**" does not match any file.
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS2
INFO [launcher]: Starting browser Chrome
INFO [PhantomJS 2.0.0 (Linux 0.0.0)]: Connected on socket mKolmPKJj8xj3WCQPy2g with id 15469313
PhantomJS 2.0.0 (Linux 0.0.0) ERROR
  ReferenceError: Can't find variable: require
  at /home/wunder/projects/angular2-seed/node_modules/es6-module-loader/dist/es6-module-loader-sans-promises.src.js:142


INFO [Chromium 45.0.2454 (Ubuntu 0.0.0)]: Connected on socket gbOvK0F_3rAZX8FSPy2h with id 59107354
WARN [web-server]: 404: /base/node_modules/@reactivex/rxjs/dist/cjs/Subject.js
Chromium 45.0.2454 (Ubuntu 0.0.0) ERROR: 'Error: XHR error (404 Not Found) loading http://localhost:9876/base/node_modules/@reactivex/rxjs/dist/cjs/Subject.js
    at error (http://localhost:9876/base/node_modules/systemjs/dist/system.src.js?deda5de3b4d843472833379dc10cf66e0aadf1d1:1028:16)
    at XMLHttpRequest.xhr.onreadystatechange (http://localhost:9876/base/node_modules/systemjs/dist/system.src.js?deda5de3b4d843472833379dc10cf66e0aadf1d1:1036:13)'

Chromium 45.0.2454 (Ubuntu 0.0.0): Executed 1 of 1 SUCCESS (0.013 secs / 0.003 secs)
WARN [web-server]: 404: /base/node_modules/@reactivex/rxjs/dist/cjs/Subject.js
[22:34:24] 'karma.start' errored after 4.22 s
[22:34:24] Error: 1
    at formatError (/home/wunder/projects/angular2-seed/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/home/wunder/projects/angular2-seed/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:107:17)
    at Gulp.Orchestrator._emitTaskDone (/home/wunder/projects/angular2-seed/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /home/wunder/projects/angular2-seed/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/home/wunder/projects/angular2-seed/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/home/wunder/projects/angular2-seed/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at removeAllListeners (/home/wunder/projects/angular2-seed/node_modules/karma/lib/server.js:215:7)
    at Server.<anonymous> (/home/wunder/projects/angular2-seed/node_modules/karma/lib/server.js:226:9)
    at Server.g (events.js:199:16)
npm ERR! Test failed.  See above for more details.
wunder@wunder-VirtualBox:~/projects/angular2-seed$ 
```

**Comment by ryzy** [comment]
This change https://github.com/ryzy/angular2-seed/commit/c21c7cdb9804219f8829c376574a79859a4ce391 at least fixes it in Chrome.

**Comment by tarlepp** [comment]
Not change at this end after those modifications.. Still complaining about 

```
ReferenceError: Can't find variable: require
  at /home/wunder/projects/angular2-seed/node_modules/es6-module-loader/dist/es6-module-loader-sans-promises.src.js:142
```

**Comment by ryzy** [comment]
OK, I managed to make it work. PR https://github.com/mgechev/angular2-seed/pull/140

Seems like PhantomJS2 cannot work without Traceur - after restoring its dependency (it was removed in  _Update to angular@2.0.0.alpha.38_ change: https://github.com/mgechev/angular2-seed/commit/b94031c98096cf4feda2c5e7a60cfaeb3ed7b789) it works again.

Does it make sense or should be resolved somehow differently?

**Comment by mgechev** [comment]
We can close this issue https://github.com/mgechev/angular2-seed/blob/master/karma.conf.js#L72
