### ISSUE TITLE
Yet another build.prod issue

### ISSUE THREAD

**Issue by csreddy** [mgechev/angular2-seed#1378]
I'm sorry for posting here. But this is my last resort. 
I'm unable to get past `build.js.prod` task with `build.prod`. Not sure whats wrong. Please advise

Here's the last few lines of the exception
```
dist/tmp/app/status/status.actions.ts(148,23): error TS2339: Property 'hasTag' does not exist on type '{ [key: string]: string; }'.
dist/tmp/app/status/status.actions.ts(154,23): error TS2339: Property 'hideColumns' does not exist on type '{ [key: string]: string; }'.
dist/tmp/app/status/status.component.ts(28,20): error TS2307: Cannot find module 'lodash'.
dist/tmp/app/status/status.component.ts(184,69): error TS7006: Parameter 'user' implicitly has an 'any' type.
dist/tmp/app/status/status.component.ts(185,64): error TS2339: Property 'title' does not exist on type 'Object'.
dist/tmp/app/status/status.component.ts(185,78): error TS2339: Property 'title' does not exist on type 'Ob[18:11:42] TypeScript: 519 semantic errors
[18:11:42] TypeScript: emit succeeded (with errors)

npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/sreddy/.nvm/versions/node/v6.0.0/bin/node" "/Users/sreddy/.nvm/versions/node/v6.0.0/bin/npm" "run" "build.prod"
npm ERR! node v6.0.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! regression-status@1.0.0 build.prod: `gulp build.prod --color --config-env prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the regression-status@1.0.0 build.prod script 'gulp build.prod --color --config-env prod'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the regression-status package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build.prod --color --config-env prod
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs regression-status
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls regression-status
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/sreddy/space/angularjs/regression-status/npm-debug.log
```

npp-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/sreddy/.nvm/versions/node/v6.0.0/bin/node',
1 verbose cli   '/Users/sreddy/.nvm/versions/node/v6.0.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'build.prod' ]
2 info using npm@3.8.6
3 info using node@v6.0.0
4 verbose run-script [ 'prebuild.prod', 'build.prod', 'postbuild.prod' ]
5 info lifecycle regression-status@1.0.0~prebuild.prod: regression-status@1.0.0
6 silly lifecycle regression-status@1.0.0~prebuild.prod: no script for prebuild.prod, continuing
7 info lifecycle regression-status@1.0.0~build.prod: regression-status@1.0.0
8 verbose lifecycle regression-status@1.0.0~build.prod: unsafe-perm in lifecycle true
9 verbose lifecycle regression-status@1.0.0~build.prod: PATH: /Users/sreddy/.nvm/versions/node/v6.0.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/sreddy/space/angularjs/regression-status/node_modules/.bin:/Users/sreddy/.nvm/versions/node/v6.0.0/bin:/Users/sreddy/.nvm/versions/node/v6.0.0/bin:/Users/sreddy/.rvm/gems/ruby-2.1.1/bin:/Users/sreddy/.rvm/gems/ruby-2.1.1@global/bin:/Users/sreddy/.rvm/rubies/ruby-2.1.1/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/lib/node_modules:/usr/local/opt/go/libexec/bin:/Users/sreddy/.rvm/bin
10 verbose lifecycle regression-status@1.0.0~build.prod: CWD: /Users/sreddy/space/angularjs/regression-status
11 silly lifecycle regression-status@1.0.0~build.prod: Args: [ '-c', 'gulp build.prod --color --config-env prod' ]
12 silly lifecycle regression-status@1.0.0~build.prod: Returned: code: 1  signal: null
13 info lifecycle regression-status@1.0.0~build.prod: Failed to exec build.prod script
14 verbose stack Error: regression-status@1.0.0 build.prod: `gulp build.prod --color --config-env prod`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/sreddy/.nvm/versions/node/v6.0.0/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/sreddy/.nvm/versions/node/v6.0.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid regression-status@1.0.0
16 verbose cwd /Users/sreddy/space/angularjs/regression-status
17 error Darwin 15.3.0
18 error argv "/Users/sreddy/.nvm/versions/node/v6.0.0/bin/node" "/Users/sreddy/.nvm/versions/node/v6.0.0/bin/npm" "run" "build.prod"
19 error node v6.0.0
20 error npm  v3.8.6
21 error code ELIFECYCLE
22 error regression-status@1.0.0 build.prod: `gulp build.prod --color --config-env prod`
22 error Exit status 1
23 error Failed at the regression-status@1.0.0 build.prod script 'gulp build.prod --color --config-env prod'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the regression-status package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     gulp build.prod --color --config-env prod
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs regression-status
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls regression-status
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by mgechev** [comment]
You have type errors of your code. You should take care of them before building your project.

**Comment by csreddy** [comment]
There are about 500+ errors that TS compilation warns. Do you mean I need to fix them all. I thought they are harmless. I have even built prod build with your earlier version of seed.
Is there a way I can override to ignore TS errors ?

**Comment by mgechev** [comment]
If you think your code will work without fixing the problems, and you're sure what you're doing you can set the `isolatedModules` setting in `tsconfig.json` to `true`. In all cases, this is not an issue related with the seed but more like a legacy code problem.

**Comment by csreddy** [comment]
Does not seem to help. Here's my tsconfig.json
```json
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "declaration": false,
        "removeComments": true,
        "noLib": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "inlineSourceMap": true,
        "pretty": true,
        "allowUnreachableCode": false,
        "allowUnusedLabels": false,
        "noImplicitAny": true,
        "noImplicitReturns": true,
        "noImplicitUseStrict": false,
        "noFallthroughCasesInSwitch": true,
        "isolatedModules": true
    },
    "exclude": [
        "node_modules",
        "dist",
        "typings/browser.d.ts",
        "typings/browser",
        "src"
    ],
    "compileOnSave": false
}
```

**Comment by csreddy** [comment]
Never mind it works with `isolatedModules`.  Thanks for the assistance, appreciate it.

**Comment by csreddy** [comment]
I just updated to master,  I'm facing the exact error again.  Any clues please ?
