### ISSUE TITLE
build.prod fails in the latest build for the latest angular 2 seed

### ISSUE THREAD

**Issue by chinmoymohanty85** [mgechev/angular2-seed#1385]
**Steps to reproduce and a minimal demo of the problem**

1. Download the repo zip file
2. $ npm install
3. $ npm run build.prod

**Current behavior**
Log is as below 

> angular2-seed@0.0.0 build.prod /home/chinmoymohanty85/Projects/data-fed
> gulp build.prod --color --config-env prod

[23:54:25] Requiring external module ts-node/register
[23:54:25] Loading tasks folder /home/chinmoymohanty85/Projects/data-fed/tools/tasks/seed
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/build.assets.dev
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/build.assets.prod
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/build.bundles.app.exp
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/build.bundles.app
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/build.bundles
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/build.docs
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/build.html_css
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/build.index.dev
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/build.index.prod
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/build.js.dev
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/build.js.e2e
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/build.js.prod.exp
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/build.js.prod
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/build.js.test
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/build.js.tools
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/check.versions
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/clean.all
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/clean.coverage
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/clean.dev
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/clean.prod
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/clean.tools
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/compile.ahead.prod
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/copy.prod
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/css-lint
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/e2e
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/generate.manifest
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/karma.run
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/karma.watch
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/minify.bundles
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/serve.coverage
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/serve.docs
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/server.prod
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/server.start
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/tslint
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/watch.dev
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/watch.e2e
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/watch.test
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/seed/webdriver
[23:54:25] Loading tasks folder /home/chinmoymohanty85/Projects/data-fed/tools/tasks/project
[23:54:25] Registering task ~/Projects/data-fed/tools/tasks/project/sample.task
[23:54:25] Using gulpfile ~/Projects/data-fed/gulpfile.ts
[23:54:25] Starting 'build.prod'...
[23:54:25] Starting 'clean.prod'...
[23:54:25] Deleted dist/prod
[23:54:25] Deleted dist/tmp
[23:54:25] Finished 'clean.prod' after 5.24 ms
[23:54:25] Starting 'tslint'...
[23:54:28] Finished 'tslint' after 2.82 s
[23:54:28] Starting 'css-lint'...

/home/chinmoymohanty85/Projects/data-fed/node_modules/stylelint/dist/utils/configurationError.js:8
  var err = new Error(text);
            ^
Error: No configuration found
    at exports.default (/home/chinmoymohanty85/Projects/data-fed/node_modules/stylelint/dist/utils/configurationError.js:8:13)
    at /home/chinmoymohanty85/Projects/data-fed/node_modules/stylelint/dist/buildConfig.js:52:54

**Expected/desired behavior**
It should build successfully

**Other information**

**Comment by mgechev** [comment]
I tried to reproduce the issue but the configuration file was successfully found.

Did you set any flags, changed any files? Would you give me the output of `ls -lah tools/env`?

**Comment by chinmoymohanty85** [comment]
On running `ls -lah tools/env` it get the below output

total 24K
drwxrwxr-x 2 chinmoymohanty85 chinmoymohanty85 4.0K Sep 25 07:52 .
drwxrwxr-x 7 chinmoymohanty85 chinmoymohanty85 4.0K Sep 25 07:52 ..
-rw-rw-r-- 1 chinmoymohanty85 chinmoymohanty85  155 Sep 25 07:52 base.ts
-rw-rw-r-- 1 chinmoymohanty85 chinmoymohanty85  120 Sep 25 07:52 dev.ts
-rw-rw-r-- 1 chinmoymohanty85 chinmoymohanty85   76 Sep 25 07:52 env-config.interface.ts
-rw-rw-r-- 1 chinmoymohanty85 chinmoymohanty85  123 Sep 25 07:52 prod.ts

**Comment by chinmoymohanty85** [comment]
seems to be working now.. Got the latest from master branch and ran build.prod. All seems fine.

Thank you.
