### ISSUE TITLE
Build.prod codelyzer error

### ISSUE THREAD

**Issue by troyanskiy** [mgechev/angular2-seed#1400]
Hello.

I'm facing an prod building error.
```
[09:25:04] Starting 'tslint'...

/Users/troy/C3/Front/node_modules/codelyzer/angular/ng2Walker.js:108
                .properties.map(function (prop) {
                           ^
TypeError: Cannot read property 'map' of undefined
    at InputMetadataWalker.Ng2Walker.visitClassDecorator (/Users/troy/C3/Front/node_modules/codelyzer/angular/ng2Walker.js:108:28)
    at Array.forEach (native)
    at InputMetadataWalker.Ng2Walker.visitClassDeclaration (/Users/troy/C3/Front/node_modules/codelyzer/angular/ng2Walker.js:72:40)
    at InputMetadataWalker.SyntaxWalker.visitNode (/Users/troy/C3/Front/node_modules/tslint/lib/language/walker/syntaxWalker.js:264:22)
    at /Users/troy/C3/Front/node_modules/tslint/lib/language/walker/syntaxWalker.js:459:63
    at visitEachNode (/Users/troy/C3/Front/node_modules/typescript/lib/typescript.js:8251:30)
    at Object.forEachChild (/Users/troy/C3/Front/node_modules/typescript/lib/typescript.js:8411:24)
    at InputMetadataWalker.SyntaxWalker.walkChildren (/Users/troy/C3/Front/node_modules/tslint/lib/language/walker/syntaxWalker.js:459:12)
    at InputMetadataWalker.SyntaxWalker.visitSourceFile (/Users/troy/C3/Front/node_modules/tslint/lib/language/walker/syntaxWalker.js:190:14)
    at InputMetadataWalker.SyntaxWalker.visitNode (/Users/troy/C3/Front/node_modules/tslint/lib/language/walker/syntaxWalker.js:414:22)
```

The error is because of my source code, but how to find the place since there is no useful information in the output?

Thanks.

**Comment by troyanskiy** [comment]
Looks like sometimes `properties` attribute is missing.

**Comment by mgechev** [comment]
Thanks for the feedback! Closing the issue since it's codelyzer related.
