### ISSUE TITLE
Cannot find module errors in gulp tasks

### ISSUE THREAD

**Issue by mbaertschi** [mgechev/angular2-seed#1403]
Hi there

**Problem**
I want to add an new gulp task which deletes all .html files within the client folder (I'm using pug as template engine. This works perfectly but I want to remove the compiled .html files at the end of the build task). This gulp task makes use of two new npm modules, namely `del` and `vinyl-paths`. However, I cannot use those modules within my new gulp task as I receive a `Cannot find module x` error.

**Steps to reproduce and a minimal demo of the problem**
* install npm packages
```bash
npm i --save-dev del vinyl-paths
```
* add a new gulp-task `clean.html.dev` to `gulpfile.ts``
```typescript
gulp.task('build.dev', (done: any) =>
  runSequence(
              ...
              'build.html_css',
              'clean.html.dev',
              ...));
```

* implement the new gulp-task
```typescript
import * as gulp from 'gulp';
import { join } from 'path';
import * as del from 'del';
import * as vinyl from 'vinyl-paths';

import Config from '../../config';

/**
 * Executes the build process, removing the html files.
 */
export = () => {
  let src = [
    join(Config.APP_SRC, 'app/**, ', '*.html')
  ];
  return gulp.src(src)
    .pipe(vinyl(del));
};
```

* run the build task
```bash
npm run build.dev
```

**Current behavior**
```bash
[08:32:13] Starting 'build.dev'...
[08:32:13] Starting 'build.pug.dev'...
[08:32:13] Finished 'build.pug.dev' after 232 ms
[08:32:13] Starting 'build.assets.dev'...
[08:32:13] Finished 'build.assets.dev' after 55 ms
[08:32:13] Starting 'build.html_css'...
[08:32:13] Finished 'build.html_css' after 361 ms
[08:32:13] Starting 'clean.html.dev'...
[08:32:14] 'clean.html.dev' errored after 557 ms
[08:32:14] TSError: ⨯ Unable to compile TypeScript
tools/tasks/project/clean.html.dev.ts (3,22): Cannot find module 'del'. (2307)
tools/tasks/project/clean.html.dev.ts (4,24): Cannot find module 'vinyl-paths'. (2307)
    at getOutput (/Users/Mike/data/dev/private/angular2-base/node_modules/ts-node/src/index.ts:253:17)
    at /Users/Mike/data/dev/private/angular2-base/node_modules/ts-node/src/index.ts:263:16
    at Object.compile (/Users/Mike/data/dev/private/angular2-base/node_modules/ts-node/src/index.ts:398:17)
    at Module.m._compile (/Users/Mike/data/dev/private/angular2-base/node_modules/ts-node/src/index.ts:299:46)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/Mike/data/dev/private/angular2-base/node_modules/ts-node/src/index.ts:302:14)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
[08:32:14] 'build.dev' errored after 1.28 s
[08:32:14] TSError in plugin 'run-sequence(clean.html.dev)'
Message:
    ⨯ Unable to compile TypeScript
tools/tasks/project/clean.html.dev.ts (3,22): Cannot find module 'del'. (2307)
tools/tasks/project/clean.html.dev.ts (4,24): Cannot find module 'vinyl-paths'. (2307)
Details:
    diagnostics: tools/tasks/project/clean.html.dev.ts (3,22): Cannot find module 'del'. (2307),tools/tasks/project/clean.html.dev.ts (4,24): Cannot find module 'vinyl-paths'. (2307)
Stack:
TSError: ⨯ Unable to compile TypeScript
tools/tasks/project/clean.html.dev.ts (3,22): Cannot find module 'del'. (2307)
tools/tasks/project/clean.html.dev.ts (4,24): Cannot find module 'vinyl-paths'. (2307)
    at getOutput (/Users/Mike/data/dev/private/angular2-base/node_modules/ts-node/src/index.ts:253:17)
    at /Users/Mike/data/dev/private/angular2-base/node_modules/ts-node/src/index.ts:263:16
    at Object.compile (/Users/Mike/data/dev/private/angular2-base/node_modules/ts-node/src/index.ts:398:17)
    at Module.m._compile (/Users/Mike/data/dev/private/angular2-base/node_modules/ts-node/src/index.ts:299:46)
    at Module._extensions..js (module.js:416:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/Users/Mike/data/dev/private/angular2-base/node_modules/ts-node/src/index.ts:302:14)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)

npm ERR! Darwin 15.6.0
npm ERR! argv "/Users/Mike/.nvm/versions/v4.4.2/bin/node" "/Users/Mike/.node/bin/npm" "run" "build.dev"
npm ERR! node v4.4.2
npm ERR! npm  v3.7.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-base@0.0.0 build.dev: `gulp build.dev --color --config-env dev`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-base@0.0.0 build.dev script 'gulp build.dev --color --config-env dev'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-base package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp build.dev --color --config-env dev
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-base
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-base
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Mike/data/dev/private/angular2-base/npm-debug.log
```

**Expected/desired behavior**
Tasks completes successfully and afterwards there are no .html files left over in the client/app folder.

Thanks for your investigations and kind regards,
Michael

**Comment by mbaertschi** [comment]
Sorry, my bad. First time for me using typescript. Adding the necessary types (@types/del and @types/vinyl-paths) fixed my issue.
