### ISSUE TITLE
Add Dockerfile and docker-compose.yml support?

### ISSUE THREAD

**Issue by Shyam-Chen** [mgechev/angular2-seed#1422]
I'm using it in my Angular 1 [project](https://github.com/Shyam-Chen/Angular1Coffee-Starter-Kit).

**Comment by mgechev** [comment]
There were no other such feature requests so lets don't introduce it to the project for now.

**Comment by sclausen** [comment]
I need a docker setup too, had it for my old projects and now, without going into details, fail with angular2-seed, because of this error:
```
[…]
[07:42:51] 'build.html_css' errored after 713 ms
[07:42:51] Error: Cannot find module '.tmp/Rx.min.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.require.resolve (internal/module.js:16:19)
    at /var/www/tools/config/seed.config.ts:561:59
    at Array.forEach (native)
    at normalizeDependencies (/var/www/tools/config/seed.config.ts:561:6)
    at ProjectConfig.Object.defineProperty.get [as DEPENDENCIES] (/var/www/tools/config/seed.config.ts:334:12)
    at getExternalCss (/var/www/tools/tasks/seed/build.html_css.ts:114:16)
    at getExternalCssStream (/var/www/tools/tasks/seed/build.html_css.ts:106:19)
    at processAllExternalStylesheets (/var/www/tools/tasks/seed/build.html_css.ts:94:16)
    at processExternalStylesheets (/var/www/tools/tasks/seed/build.html_css.ts:86:31)
[07:42:51] 'build.dev' errored after 991 ms
[07:42:51] Error in plugin 'run-sequence(build.html_css)'
Message:
    Cannot find module '.tmp/Rx.min.js'
Details:
    code: MODULE_NOT_FOUND
Stack:
Error: Cannot find module '.tmp/Rx.min.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.require.resolve (internal/module.js:16:19)
    at /var/www/tools/config/seed.config.ts:561:59
    at Array.forEach (native)
    at normalizeDependencies (/var/www/tools/config/seed.config.ts:561:6)
    at ProjectConfig.Object.defineProperty.get [as DEPENDENCIES] (/var/www/tools/config/seed.config.ts:334:12)
    at getExternalCss (/var/www/tools/tasks/seed/build.html_css.ts:114:16)
    at getExternalCssStream (/var/www/tools/tasks/seed/build.html_css.ts:106:19)
    at processAllExternalStylesheets (/var/www/tools/tasks/seed/build.html_css.ts:94:16)
    at processExternalStylesheets (/var/www/tools/tasks/seed/build.html_css.ts:86:31)

Error: Cannot find module '.tmp/Rx.min.js'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.require.resolve (internal/module.js:16:19)
    at /var/www/tools/config/seed.config.ts:561:59
    at Array.forEach (native)
    at normalizeDependencies (/var/www/tools/config/seed.config.ts:561:6)
    at ProjectConfig.Object.defineProperty.get [as DEPENDENCIES] (/var/www/tools/config/seed.config.ts:334:12)
    at getExternalCss (/var/www/tools/tasks/seed/build.html_css.ts:114:16)
    at getExternalCssStream (/var/www/tools/tasks/seed/build.html_css.ts:106:19)
    at processAllExternalStylesheets (/var/www/tools/tasks/seed/build.html_css.ts:94:16)
    at processExternalStylesheets (/var/www/tools/tasks/seed/build.html_css.ts:86:31)
[…]
```
I'll make a pull-request for a docker-setup soon, maybe we can dig into this problem together.

**Comment by TheDonDope** [comment]
@sclausen checkout #1522
