### ISSUE TITLE
Error encountered resolving symbol values statically.

### ISSUE THREAD

**Issue by SerkanDayicik** [mgechev/angular2-seed#1425]
added some component and getting this error npm run build.prod.exp and get error 

`Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol SharedModule in C:/Users/x0nim/Desktop/avukat/dist/tmp/app/shared/shared.module.ts, resolving symbol SharedModule in C:/Users/x0nim/Desktop/avukat/dist/tmp/app/shared/shared.module.ts
    at simplifyInContext (C:\Users\iminar\Dev\angular\modules\@angular\compiler-cli\src\static_reflector.ts:528:15)
    at StaticReflector.simplify (C:\Users\iminar\Dev\angular\modules\@angular\compiler-cli\src\static_reflector.ts:532:18)
    at StaticReflector.annotations (C:\Users\iminar\Dev\angular\modules\@angular\compiler-cli\src\static_reflector.ts:92:28)
    at _loop_1 (C:\Users\iminar\Dev\angular\modules\@angular\compiler-cli\src\codegen.ts:63:48)
    at CodeGenerator.readFileMetadata (C:\Users\x0nim\Desktop\avukat\node_modules\@angular\compiler-cli\src\codegen.js:66:13)
    at C:\Users\iminar\Dev\angular\modules\@angular\compiler-cli\src\codegen.ts:105:56
    at Array.map (native)
    at CodeGenerator.codegen (C:\Users\iminar\Dev\angular\modules\@angular\compiler-cli\src\codegen.ts:105:33)
    at codegen (C:\Users\x0nim\Desktop\avukat\tools\tasks\seed\compile.ahead.prod.ts:14:69)
    at Object.main (C:\Users\x0nim\Desktop\tools\@angular\tsc-wrapped\src\main.ts:44:12)
Compilation failed`

SharedModule

`import { NgModule, ModuleWithProviders } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { RouterModule } from '@angular/router';

import { HeaderComponent } from './header/index';
import { FooterComponent } from './footer/index';
import { ProfileAreaComponent } from './header/profile/index';

import {SlimLoadingBarModule} from 'ng2-slim-loading-bar';

@NgModule({
  imports: [CommonModule, RouterModule, SlimLoadingBarModule.forRoot()],
  declarations: [HeaderComponent, FooterComponent, ProfileAreaComponent],
  exports: [
  HeaderComponent,
  FooterComponent,
  ProfileAreaComponent,
  CommonModule,
  FormsModule,
  RouterModule,
  SlimLoadingBarModule
  ]
})
export class SharedModule {
  static forRoot(): ModuleWithProviders {
    return {
      ngModule: SharedModule,
      providers: []
    };
  }
}
`

**Comment by mgechev** [comment]
Yes, this is a common issue that I've experienced in the past. It is not seed related problem, you can take a look here https://github.com/angular/angular/issues/11262 and here https://github.com/angular/angular/issues/10132.
