### ISSUE TITLE
Deploy to Azure Fails

### ISSUE THREAD

**Issue by kahanu** [mgechev/angular2-seed#1433]
Can/should this seed project be used to deploy to Azure?

Currently I'm testing the seed project for CI in Azure and it's failing.  This is my first attempt at setting up a Node project on Azure and I realize there's lots of moving parts here, so please point me in the right direction for this.

What I did:

1. Created local folder for project
2. Initialized for git
3. Copied the seed project
4. Checked the code into my github repo
5. Azure CI was triggered and failed

Objective:

1. Create MEAN stack project
2. Check in to github
3. Trigger CI in Azure with tests

Let me know if this isn't the right seed project for this.

Here's the Azure Deployment logs:

```
Command: "D:\home\site\deployments\tools\deploy.cmd"
Handling node.js deployment.
KuduSync.NET from: 'D:\home\site\repository' to: 'D:\home\site\wwwroot'
Copying file: 'README.md'
Invalid start-up command "gulp serve.dev --color" in package.json. Please use the format "node <script relative path>".
Looking for app.js/server.js under site root.
Missing server.js/app.js files, web.config is not generated
The package.json file does not specify node.js engine version constraints.
The node.js application will run with the default node.js version 4.4.7.
Selected npm version 2.15.8

> angular2-seed@0.0.0 postinstall D:\home\site\wwwroot
> gulp check.versions && gulp build.bundle.rxjs && npm prune && gulp webdriver && gulp print.banner

[01:28:26] Failed to load external module typescript-register
[01:28:26] Failed to load external module typescript-require
[01:28:26] Local gulp not found in D:\home\site\wwwroot
[01:28:26] Try running: npm install gulp

npm ERR! Windows_NT 6.2.9200
npm ERR! argv "D:\\Program Files (x86)\\nodejs\\4.4.7\\node.exe" "D:\\Program Files (x86)\\npm\\2.15.8\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
npm ERR! node v4.4.7
npm ERR! npm  v2.15.8
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 postinstall: `gulp check.versions && gulp build.bundle.rxjs && npm prune && gulp webdriver && gulp print.banner`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the angular2-seed@0.0.0 postinstall script 'gulp check.versions && gulp build.bundle.rxjs && npm prune && gulp webdriver && gulp print.banner'.
npm ERR! This is most likely a problem with the angular2-seed package,
Failed exitCode=1, command="D:\Program Files (x86)\nodejs\4.4.7\node.exe" "D:\Program Files (x86)\npm\2.15.8\node_modules\npm\bin\npm-cli.js" install --production
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
An error has occurred during web site deployment.
npm ERR!     gulp check.versions && gulp build.bundle.rxjs && npm prune && gulp webdriver && gulp print.banner
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\home\site\wwwroot\npm-debug.log
Invalid start-up command "gulp serve.dev --color" in package.json. Please use the format "node <script relative path>".\r\nMissing server.js/app.js files, web.config is not generated\r\n\r\nnpm ERR! Windows_NT 6.2.9200\r\nnpm ERR! argv "D:\\Program Files (x86)\\nodejs\\4.4.7\\node.exe" "D:\\Program Files (x86)\\npm\\2.15.8\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"\r\nnpm ERR! node v4.4.7\r\nnpm ERR! npm  v2.15.8\r\nnpm ERR! code ELIFECYCLE\r\nnpm ERR! angular2-seed@0.0.0 postinstall: `gulp check.versions && gulp build.bundle.rxjs && npm prune && gulp webdriver && gulp print.banner`\r\nnpm ERR! Exit status 1\r\nnpm ERR! \r\nnpm ERR! Failed at the angular2-seed@0.0.0 postinstall script 'gulp check.versions && gulp build.bundle.rxjs && npm prune && gulp webdriver && gulp print.banner'.\r\nnpm ERR! This is most likely a problem with the angular2-seed package,\r\nnpm ERR! not with npm itself.\r\nnpm ERR! Tell the author that this fails on your system:\r\nnpm ERR!     gulp check.versions && gulp build.bundle.rxjs && npm prune && gulp webdriver && gulp print.banner\r\nnpm ERR! You can get information on how to open an issue for this project with:\r\nnpm ERR!     npm bugs angular2-seed\r\nnpm ERR! Or if that isn't available, you can get their info via:\r\nnpm ERR! \r\nnpm ERR!     npm owner ls angular2-seed\r\nnpm ERR! There is likely additional logging output above.\r\n\r\nnpm ERR! Please include the following file with any support request:\r\nnpm ERR!     D:\home\site\wwwroot\npm-debug.log\r\nD:\Program Files (x86)\SiteExtensions\Kudu\58.50929.2438\bin\Scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"
```

**Comment by mgechev** [comment]
To Azure you can deploy the production build. Once you run:

```bash
npm run build.prod # or npm run build.prod.exp for AoT compilation
```

You'll have a bundle of **all** files used by your project in `dist/prod`. All you have to do is to upload the files to Azure.

All you need for Angular is a **static web server**. You need your static files to be served by the browser and later in your application, if required, you can communicate with the application server that you developed with node, from your MEAN stack.

**Comment by kahanu** [comment]
@mgechev - thanks for the response.  I'm still not sure how all this works with CI from github to Azure.  I thought CI on Azure usually ran build and test scripts and deployed if successful.  With this seed project, it seems I need to build and test locally, then push to github, then have Azure CI simply point to the dist folder to deploy the built app.  Is that what you are saying needs to be done?

I was hoping to allow Azure CI do the building and testing since I'll be with a small team and it would be best if we all could just check in our code and have CI take over.

Sorry about the questions, I'm coming from 16 years on the Microsoft stack and just now getting interested in the MEAN stack with Angular 2 and trying to get familiar with production processes.

**Comment by mgechev** [comment]
We are using CI, we are using two continues integration systems:
- Travis CI
- AppVeyor

Travis runs builds, unit & e2e tests on Linux and OS X, AppVeyor on Windows. I don't know what CI solution you're using on Azure and I have no idea what the configuration should be but you can take a look at [`.travis.yml`](https://github.com/mgechev/angular2-seed/blob/master/.travis.yml) and [`appveyor.yml`](https://github.com/mgechev/angular2-seed/blob/master/appveyor.yml).

**Comment by kahanu** [comment]
Ok, I'll try to find out more on how Azure handles CI.  There's not much info on that.  Thanks.

**Comment by bwwilliam** [comment]
Hi mgechev, 

I am using Visual studio TFS Online trying to build the project by "npm run build.prod"
I got the following error, any help from you would  be much appreciated.
017-02-13T02:32:58.8680480Z tools/config/seed.config.ts[374, 1]: trailing whitespace
2017-02-13T02:32:58.8680480Z 
2017-02-13T02:33:00.8950477Z [[90m02:33:00[39m] '[36mtslint[39m' [31merrored after[39m [35m5.19 s[39m
2017-02-13T02:33:00.8950477Z [[90m02:33:00[39m] [31mError[39m in plugin '[36mgulp-tslint[39m'
2017-02-13T02:33:00.9000482Z Message:
2017-02-13T02:33:00.9000482Z     Failed to lint: src/client/app/app.module.ts [16, 1]: space indentation expected, src/client/app/app.module.ts [15, 70]: trailing whitespace, src/client/app/app.module.ts [19, 28]: trailing whitespace, src/client/app/about/about.component.ts [21, 17]: block is empty, src/client/app/about/about.component.ts [12, 48]: trailing whitespace, src/client/app/about/about.component.ts [26, 15]: trailing whitespace, src/client/app/account/account-routing.module.ts [15, 37]: file should end with a newline, src/client/app/account/account.component.ts [21, 2]: file should end with a newline, src/client/app/account/account.component.ts [14, 5]: Declaration of public instance member variable not allowed to appear after declaration of public instance member function, src/client/app/account/account.component.ts [10, 50]: trailing whitespace, src/client/app/account/account.component.ts [2, 59]: Missing semicolon, src/client/app/account/account.module.ts [13, 30]: file should end with a newline, src/client/app/account/account.module.ts [9, 33]: trailing whitespace, src/client/app/home/home.component.ts [17, 1]: trailing whitespace, src/client/app/home/home.component.ts [31, 1]: trailing whitespace, src/client/app/login/login.component.ts [39, 2]: file should end with a newline, src/client/app/login/login.component.ts [30, 22]: block is empty, src/client/app/login/login.component.ts [17, 116]: trailing whitespace, src/client/app/login/login.component.ts [38, 1]: trailing whitespace, src/client/app/login/login.component.ts [20, 15]: missing whitespace, src/client/app/login/login.component.ts [24, 12]: missing whitespace, src/client/app/login/login.component.ts [30, 17]: misplaced 'else', src/client/app/login/login.component.ts [14, 21]: " should be ', src/client/app/login/login.component.ts [15, 22]: " should be ', src/client/app/login/login.component.ts [27, 28]: == should be ===, src/client/app/shared/index.ts [11, 37]: file should end with a newline, src/client/app/shared/account/account.service.ts [29, 1]: trailing whitespace, src/client/app/shared/account/account.service.ts [27, 25]: " should be ', src/client/app/shared/account/account.service.ts [27, 41]: " should be ', src/client/app/shared/account/account.service.ts [28, 25]: " should be ', src/client/app/shared/account/account.service.ts [28, 42]: " should be ', src/client/app/shared/guard/auth.guard.ts [18, 2]: file should end with a newline, src/client/app/shared/guard/auth.guard.ts [6, 1]: trailing whitespace, src/client/app/shared/guard/auth.guard.ts [8, 1]: trailing whitespace, src/client/app/shared/guard/auth.guard.ts [11, 41]: missing whitespace, src/client/app/shared/guard/index.ts [4, 30]: file should end with a newline, src/client/app/shared/models/Account.ts [4, 2]: file should end with a newline, src/client/app/shared/models/Account.ts [3, 21]: trailing whitespace, src/client/app/shared/models/index.ts [6, 24]: file should end with a newline, src/client/app/shared/models/Jwt.ts [8, 2]: file should end with a newline, src/client/app/shared/models/Jwt.ts [6, 18]: trailing whitespace, src/client/app/shared/models/User.ts [6, 2]: file should end with a newline, src/client/app/shared/navbar/navbar.component.ts [19, 15]: block is empty, src/client/app/shared/navbar/navbar.component.ts [2, 56]: trailing whitespace, src/client/app/shared/navbar/navbar.component.ts [20, 1]: trailing whitespace, src/client/app/shared/navbar/navbar.component.ts [23, 1]: trailing whitespace, src/client/app/shared/navbar/navbar.component.ts [16, 89]: missing whitespace, src/client/app/shared/navbar/navbar.component.ts [19, 15]: missing whitespace, src/client/app/shared/navbar/navbar.component.html [1, 2]: You can bind only to public class members., src/client/app/shared/navbar/navbar.component.html [1, 1]: You can bind only to public class members., src/client/app/shared/user/user.service.spec.ts [39, 1]: Exceeds maximum line length of 140, src/client/app/shared/user/user.service.ts [32, 1]: Exceeds maximum line length of 140, src/client/app/shared/user/user.service.ts [14, 3]: Declaration of public instance member variable not allowed to appear after declaration of private instance member variable, src/client/app/shared/user/user.service.ts [40, 9]: misplaced 'else', src/client/app/shared/user/user.service.ts [30, 25]: " should be ', src/client/app/shared/user/user.service.ts [30, 41]: " should be ', src/client/app/shared/user/user.service.ts [32, 44]: " should be ', src/client/app/shared/user/user.service.ts [37, 32]: " should be ', src/client/app/shared/user/user.service.ts [62, 53]: " should be ', src/client/app/shared/user/user.service.ts [50, 13]: == should be ===, tools/config/seed.config.ts [365, 1]: Exceeds maximum line length of 140, tools/config/seed.config.ts [314, 1]: trailing whitespace, tools/config/seed.config.ts [374, 1]: trailing whitespace.
2017-02-13T02:33:00.9000482Z [[90m02:33:00[39m] '[36mbuild.prod[39m' [31merrored after[39m [35m5.71 s[39m
2017-02-13T02:33:00.9000482Z [[90m02:33:00[39m] [31mError[39m in plugin '[36mrun-sequence(tslint)[39m'
2017-02-13T02:33:00.9000482Z Message:
2017-02-13T02:33:00.9010488Z     Failed to lint: src/client/app/app.module.ts [16, 1]: space indentation expected, src/client/app/app.module.ts [15, 70]: trailing whitespace, src/client/app/app.module.ts [19, 28]: trailing whitespace, src/client/app/about/about.component.ts [21, 17]: block is empty, src/client/app/about/about.component.ts [12, 48]: trailing whitespace, src/client/app/about/about.component.ts [26, 15]: trailing whitespace, src/client/app/account/account-routing.module.ts [15, 37]: file should end with a newline, src/client/app/account/account.component.ts [21, 2]: file should end with a newline, src/client/app/account/account.component.ts [14, 5]: Declaration of public instance member variable not allowed to appear after declaration of public instance member function, src/client/app/account/account.component.ts [10, 50]: trailing whitespace, src/client/app/account/account.component.ts [2, 59]: Missing semicolon, src/client/app/account/account.module.ts [13, 30]: file should end with a newline, src/client/app/account/account.module.ts [9, 33]: trailing whitespace, src/client/app/home/home.component.ts [17, 1]: trailing whitespace, src/client/app/home/home.component.ts [31, 1]: trailing whitespace, src/client/app/login/login.component.ts [39, 2]: file should end with a newline, src/client/app/login/login.component.ts [30, 22]: block is empty, src/client/app/login/login.component.ts [17, 116]: trailing whitespace, src/client/app/login/login.component.ts [38, 1]: trailing whitespace, src/client/app/login/login.component.ts [20, 15]: missing whitespace, src/client/app/login/login.component.ts [24, 12]: missing whitespace, src/client/app/login/login.component.ts [30, 17]: misplaced 'else', src/client/app/login/login.component.ts [14, 21]: " should be ', src/client/app/login/login.component.ts [15, 22]: " should be ', src/client/app/login/login.component.ts [27, 28]: == should be ===, src/client/app/shared/index.ts [11, 37]: file should end with a newline, src/client/app/shared/account/account.service.ts [29, 1]: trailing whitespace, src/client/app/shared/account/account.service.ts [27, 25]: " should be ', src/client/app/shared/account/account.service.ts [27, 41]: " should be ', src/client/app/shared/account/account.service.ts [28, 25]: " should be ', src/client/app/shared/account/account.service.ts [28, 42]: " should be ', src/client/app/shared/guard/auth.guard.ts [18, 2]: file should end with a newline, src/client/app/shared/guard/auth.guard.ts [6, 1]: trailing whitespace, src/client/app/shared/guard/auth.guard.ts [8, 1]: trailing whitespace, src/client/app/shared/guard/auth.guard.ts [11, 41]: missing whitespace, src/client/app/shared/guard/index.ts [4, 30]: file should end with a newline, src/client/app/shared/models/Account.ts [4, 2]: file should end with a newline, src/client/app/shared/models/Account.ts [3, 21]: trailing whitespace, src/client/app/shared/models/index.ts [6, 24]: file should end with a newline, src/client/app/shared/models/Jwt.ts [8, 2]: file should end with a newline, src/client/app/shared/models/Jwt.ts [6, 18]: trailing whitespace, src/client/app/shared/models/User.ts [6, 2]: file should end with a newline, src/client/app/shared/navbar/navbar.component.ts [19, 15]: block is empty, src/client/app/shared/navbar/navbar.component.ts [2, 56]: trailing whitespace, src/client/app/shared/navbar/navbar.component.ts [20, 1]: trailing whitespace, src/client/app/shared/navbar/navbar.component.ts [23, 1]: trailing whitespace, src/client/app/shared/navbar/navbar.component.ts [16, 89]: missing whitespace, src/client/app/shared/navbar/navbar.component.ts [19, 15]: missing whitespace, src/client/app/shared/navbar/navbar.component.html [1, 2]: You can bind only to public class members., src/client/app/shared/navbar/navbar.component.html [1, 1]: You can bind only to public class members., src/client/app/shared/user/user.service.spec.ts [39, 1]: Exceeds maximum line length of 140, src/client/app/shared/user/user.service.ts [32, 1]: Exceeds maximum line length of 140, src/client/app/shared/user/user.service.ts [14, 3]: Declaration of public instance member variable not allowed to appear after declaration of private instance member variable, src/client/app/shared/user/user.service.ts [40, 9]: misplaced 'else', src/client/app/shared/user/user.service.ts [30, 25]: " should be ', src/client/app/shared/user/user.service.ts [30, 41]: " should be ', src/client/app/shared/user/user.service.ts [32, 44]: " should be ', src/client/app/shared/user/user.service.ts [37, 32]: " should be ', src/client/app/shared/user/user.service.ts [62, 53]: " should be ', src/client/app/shared/user/user.service.ts [50, 13]: == should be ===, tools/config/seed.config.ts [365, 1]: Exceeds maximum line length of 140, tools/config/seed.config.ts [314, 1]: trailing whitespace, tools/config/seed.config.ts [374, 1]: trailing whitespace.
2017-02-13T02:33:00.9010488Z Stack:
2017-02-13T02:33:00.9010488Z     at finish (D:\a\1\s\node_modules\run-sequence\index.js:56:13)
2017-02-13T02:33:00.9010488Z     at Gulp.onError (D:\a\1\s\node_modules\run-sequence\index.js:67:4)
2017-02-13T02:33:00.9010488Z     at emitOne (events.js:101:20)
2017-02-13T02:33:00.9010488Z     at Gulp.emit (events.js:188:7)
2017-02-13T02:33:00.9010488Z     at Gulp.Orchestrator._emitTaskDone (D:\a\1\s\node_modules\orchestrator\index.js:264:8)
2017-02-13T02:33:00.9010488Z     at D:\a\1\s\node_modules\orchestrator\index.js:275:23
2017-02-13T02:33:00.9010488Z     at finish (D:\a\1\s\node_modules\orchestrator\lib\runTask.js:21:8)
2017-02-13T02:33:00.9010488Z     at Stream.<anonymous> (D:\a\1\s\node_modules\orchestrator\lib\runTask.js:52:4)
2017-02-13T02:33:00.9010488Z     at Stream.f (D:\a\1\s\node_modules\end-of-stream\node_modules\once\once.js:17:25)
2017-02-13T02:33:00.9010488Z     at emitOne (events.js:101:20)
2017-02-13T02:33:01.0141363Z 
2017-02-13T02:33:01.0141363Z npm ERR! Windows_NT 6.3.9600
2017-02-13T02:33:01.0160476Z npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build.prod"
2017-02-13T02:33:01.0160476Z npm ERR! node v6.9.1
2017-02-13T02:33:01.0160476Z npm ERR! npm  v3.10.8
2017-02-13T02:33:01.0160476Z npm ERR! code ELIFECYCLE
2017-02-13T02:33:01.0160476Z npm ERR! angular-seed@0.0.0 build.prod: `gulp build.prod --color --env-config prod --build-type prod`
2017-02-13T02:33:01.0160476Z npm ERR! Exit status 1
2017-02-13T02:33:01.0160476Z npm ERR! 
2017-02-13T02:33:01.0160476Z npm ERR! Failed at the angular-seed@0.0.0 build.prod script 'gulp build.prod --color --env-config prod --build-type prod'.
2017-02-13T02:33:01.0170468Z npm ERR! Make sure you have the latest version of node.js and npm installed.
2017-02-13T02:33:01.0170468Z npm ERR! If you do, this is most likely a problem with the angular-seed package,
2017-02-13T02:33:01.0170468Z npm ERR! not with npm itself.
2017-02-13T02:33:01.0170468Z npm ERR! Tell the author that this fails on your system:
2017-02-13T02:33:01.0170468Z npm ERR!     gulp build.prod --color --env-config prod --build-type prod
2017-02-13T02:33:01.0170468Z npm ERR! You can get information on how to open an issue for this project with:
2017-02-13T02:33:01.0170468Z npm ERR!     npm bugs angular-seed
2017-02-13T02:33:01.0170468Z npm ERR! Or if that isn't available, you can get their info via:
2017-02-13T02:33:01.0170468Z npm ERR!     npm owner ls angular-seed
2017-02-13T02:33:01.0170468Z npm ERR! There is likely additional logging output above.
2017-02-13T02:33:01.0170468Z 
2017-02-13T02:33:01.0170468Z npm ERR! Please include the following file with any support request:
