### ISSUE TITLE
TypeError: Cannot read property 'animations' of undefined

### ISSUE THREAD

**Issue by jcamus** [mgechev/angular2-seed#1439]
Hello,
I am using the latest seed, just run 
npm install
npm run test

I obtain the following error :

```
c:\oldGen\TransfolioWeb\AngularSeedLatest\node_modules\@angular\compiler\bundles\compiler.umd.js:8766
          template.animations.forEach(function (entry) { triggerLookup.add(entry.name); });
                  ^
TypeError: Cannot read property 'animations' of undefined
    at TemplateParseVisitor._validateElementAnimationInputOutputs (c:\oldGen\TransfolioWeb\AngularSeedLatest\node_modules\@angular\compiler\bundles\compiler.umd.js:8766:19)
    at TemplateParseVisitor.visitElement (c:\oldGen\TransfolioWeb\AngularSeedLatest\node_modules\@angular\compiler\bundles\compiler.umd.js:8749:20)
    at Element.visit (c:\oldGen\TransfolioWeb\AngularSeedLatest\node_modules\@angular\compiler\bundles\compiler.umd.js:4688:78)
    at c:\oldGen\TransfolioWeb\AngularSeedLatest\node_modules\@angular\compiler\bundles\compiler.umd.js:4703:31
    at Array.forEach (native)
    at visitAll (c:\oldGen\TransfolioWeb\AngularSeedLatest\node_modules\@angular\compiler\bundles\compiler.umd.js:4702:13)
    at TemplateParser.tryParse (c:\oldGen\TransfolioWeb\AngularSeedLatest\node_modules\@angular\compiler\bundles\compiler.umd.js:8492:24)
    at Object.exports.parseTemplate (c:\oldGen\TransfolioWeb\AngularSeedLatest\node_modules\codelyzer\angular\templateParser.js:14:23)
    at InputMetadataWalker.Ng2Walker.visitClassDecorator (c:\oldGen\TransfolioWeb\AngularSeedLatest\node_modules\codelyzer\angular\ng2Walker.js:115:62)
    at Array.forEach (native)
```

Any idea?
Best regards.

**Comment by pbazurin-softheme** [comment]
Same issue after update to angular 2.0.2.

**Comment by jpinkster** [comment]
please see https://github.com/angular/angular/issues/12120

**Comment by jcamus** [comment]
Ok problem fixed. I just erased all my previous env and replace it totally with latest seed. It works now. 
I must say that js tools are still difficult to understand when such errors occur...A lot of config files everywhere in the project. Could it be simplified?

**Comment by MCreationz** [comment]
Hy I am leaning angular .while applying agular animations i got this error 
 Cannot read property 'state' of undefined plx help me out................................................


thanks
