### ISSUE TITLE
EPERM on `serve.prod` in Windows

### ISSUE THREAD

**Issue by mgechev** [mgechev/angular2-seed#20]
In `clean.tmp` task get:
```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: watch EPERM
    at exports._errnoException (util.js:746:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1157:26)
```
when running `serve.prod`.

**Comment by mgechev** [comment]
@ludohenin let me know when you verify that it works on windows :-)
