### ISSUE TITLE
Upgrade to Alpha 45

### ISSUE THREAD

**Issue by JakePartusch** [mgechev/angular2-seed#212]
Here is the changelog:
https://github.com/angular/angular/blob/master/CHANGELOG.md

I thought it would be an easy upgrade, but the tests are now failing

```
Jakes-MacBook-Pro:angular2-seed jakepartusch$ npm test

> angular2-seed@0.0.0 test /Users/jakepartusch/angular2-testing-workspace/angular2-seed
> gulp test

[22:06:38] Requiring external module ts-node/register
[22:06:40] Using gulpfile ~/angular2-testing-workspace/angular2-seed/gulpfile.ts
[22:06:40] Starting 'test'...
[22:06:40] Starting 'clean.test'...
[22:06:40] Finished 'clean.test' after 4.34 ms
[22:06:40] Starting 'tslint'...
[22:06:41] Finished 'tslint' after 861 ms
[22:06:41] Starting 'build.test'...
[22:06:43] Finished 'build.test' after 1.56 s
[22:06:43] Starting 'karma.start'...
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser PhantomJS2
INFO [launcher]: Starting browser Chrome
INFO [PhantomJS 2.0.0 (Mac OS X 0.0.0)]: Connected on socket Fu4_4o3GcyS0ndPqtipM with id 67905766
WARN [web-server]: 404: /base/traceur.js
WARN [web-server]: 404: /base/selenium-webdriver.js
PhantomJS 2.0.0 (Mac OS X 0.0.0) ERROR: Error{stack: undefined, line: 740, sourceURL: 'http://localhost:9876/base/node_modules/systemjs/dist/system.src.js?8a7dc2b121cf30cbcb09362dbeab69432cb0db29'}
INFO [Chrome 46.0.2490 (Mac OS X 10.11.0)]: Connected on socket Ng8FHyC4OpQO2-emtipN with id 38729127
WARN [web-server]: 404: /base/traceur.js
ERROR: 'Error: XHR error (404 Not Found) loading http://localhost:9876/base/traceur.js
    at error (http://localhost:9876/base/node_modules/systemjs/dist/system.src.js?8a7dc2b121cf30cbcb09362dbeab69432cb0db29:1020:16)
    at XMLHttpRequest.xhr.onreadystatechange [as _onreadystatechange] (http://localhost:9876/base/node_modules/systemjs/dist/system.src.js?8a7dc2b121cf30cbcb09362dbeab69432cb0db29:1028:13)
    at Zone.run (http://localhost:9876/base/node_modules/zone.js/dist/zone-microtask.js?e1fafbeeb394f8255f39a99f6ddff61c589f16a4:120:17)
    at XMLHttpRequest.zoneBoundFn (http://localhost:9876/base/node_modules/zone.js/dist/zone-microtask.js?e1fafbeeb394f8255f39a99f6ddff61c589f16a4:93:19)'

Finished in 0.002 secs / 0 secs

SUMMARY:
✔ 0 tests completed
WARN [web-server]: 404: /base/selenium-webdriver.js
[22:06:45] 'karma.start' errored after 2.35 s
[22:06:45] Error: 1
    at formatError (/Users/jakepartusch/angular2-testing-workspace/angular2-seed/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/Users/jakepartusch/angular2-testing-workspace/angular2-seed/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:82:20)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/jakepartusch/angular2-testing-workspace/angular2-seed/node_modules/orchestrator/index.js:264:8)
    at /Users/jakepartusch/angular2-testing-workspace/angular2-seed/node_modules/orchestrator/index.js:275:23
    at finish (/Users/jakepartusch/angular2-testing-workspace/angular2-seed/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/jakepartusch/angular2-testing-workspace/angular2-seed/node_modules/orchestrator/lib/runTask.js:29:3)
    at removeAllListeners (/Users/jakepartusch/angular2-testing-workspace/angular2-seed/node_modules/karma/lib/server.js:215:7)
    at Server.<anonymous> (/Users/jakepartusch/angular2-testing-workspace/angular2-seed/node_modules/karma/lib/server.js:226:9)
[22:06:45] 'test' errored after 4.78 s
[22:06:45] Error in plugin 'run-sequence'
Message:
    An error occured in task 'karma.start'.
npm ERR! Test failed.  See above for more details.
```

**Comment by ludohenin** [comment]
Yes! `traceur.js` dependency is easy to solve but `selenium-webdriver.js` is another story.
Don't understand from where this dependency is required. For me, once traceur added, `NameList` passes, maybe it has something to do with `angular2/testing`

**Comment by siddharthjain210** [comment]
yes !! Even after resolving `traceur.js`, `selenium-webdriver.js` error is coming up. I search through angular source code and found that `e2e_util.js` is importing `selenium-webdriver.js`.
But even after adding the following to `karma.conf.js`, the error  is same.
```    exclude: [
     'node_modules\angular2\src\testing\e2e_util.js',
     'node_modules\angular2\src\testing\perf_util.js',
    ],'``

**Comment by siddharthjain210** [comment]
The internal spec files in the angular source code needs to be  added in the excluded files list.
```
    // list of files to exclude
    exclude: [
        'node_modules/angular2/**/*_spec.js'
           ],
```
Adding these lines of code to karma.conf.js solved the problem. The unit test cases are passing now in my local project.

**Comment by ludohenin** [comment]
@siddharthjain210 Excellent! would you send a PR (base on latest master and a single commit :) ?

**Comment by siddharthjain210** [comment]
@ludohenin I am new to new to Github, i dont know what a PR is.

**Comment by mgechev** [comment]
@siddharthjain210 a pull request. [Here are](https://yangsu.github.io/pull-request-tutorial/) sample steps you can follow.

**Comment by siddharthjain210** [comment]
Because of proxy at my workplace i am unable to create a pull request. It would be great if someone else can merge the changes on my behalf and verify if its working.

**Comment by JakePartusch** [comment]
I'll volunteer to try this fix either tonight or tomorrow if someone else doesn't get to it first.
