### ISSUE TITLE
gulp preinstall fails: Unexpected token import

### ISSUE THREAD

**Issue by johnjelinek** [mgechev/angular2-seed#221]
```
$ node --version
v5.0.0
$ npm --version
3.3.6
```

```
$ gulp preinstall
[11:06:30] Failed to load external module ts-node/register
[11:06:30] Failed to load external module typescript-node/register
[11:06:30] Failed to load external module typescript-register
[11:06:30] Failed to load external module typescript-require
/Users/administrator/Projects/angular2-seed/gulpfile.ts:1
(function (exports, require, module, __filename, __dirname) { import * as gulp from 'gulp';
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:404:25)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Liftoff.handleArguments (/Users/administrator/.nvm/versions/node/v5.0.0/lib/node_modules/gulp-cli/index.js:120:3)
    at Liftoff.<anonymous> (/Users/administrator/.nvm/versions/node/v5.0.0/lib/node_modules/gulp-cli/node_modules/liftoff/index.js:192:16)
    at module.exports (/Users/administrator/.nvm/versions/node/v5.0.0/lib/node_modules/gulp-cli/node_modules/flagged-respawn/index.js:17:3)
```

**Comment by johnjelinek** [comment]
I ran `npm run reinstall` and got passed this problem.
