### ISSUE TITLE
Testing Components with constructor properties

### ISSUE THREAD

**Issue by johnjelinek** [mgechev/angular2-seed#238]
I added a constructor with a property like this:
```
import {Component, NgFor} from 'angular2/angular2';

import {PostCmp} from '../post/post';
import {PostList} from '../../services/post_list';

@Component({
  selector: 'home',
  templateUrl: './components/home/home.html',
  styleUrls: ['./components/home/home.css'],
  directives: [NgFor, PostCmp]
})
export class HomeCmp {
  constructor(public list: PostList) {
  }
}
```
Now tests fail:
```
FAILED TESTS:
  Home component
    ✖ should work
      PhantomJS 2.0.0 (Mac OS X 0.0.0)
      Chrome 46.0.2490 (Mac OS X 10.10.5)
    Failed: No provider for PostList! (HomeCmp -> PostList)
    Error: DI Exception
        at NoProviderError.BaseException [as constructor] (/Users/administrator/go/src/hackman/node_modules/angular2/src/core/facade/exceptions.js:15:23)
        at NoProviderError.AbstractProviderError [as constructor] (/Users/administrator/go/src/hackman/node_modules/angular2/src/core/di/exceptions.js:38:16)
        at new NoProviderError (/Users/administrator/go/src/hackman/node_modules/angular2/src/core/di/exceptions.js:74:16)
        at Injector._throwOrNull (/Users/administrator/go/src/hackman/node_modules/angular2/src/core/di/injector.js:851:19)
        at Injector._getByKeyDefault (/Users/administrator/go/src/hackman/node_modules/angular2/src/core/di/injector.js:902:21)
        at Injector._getByKey (/Users/administrator/go/src/hackman/node_modules/angular2/src/core/di/injector.js:842:25)
        at Injector._getByDependency (/Users/administrator/go/src/hackman/node_modules/angular2/src/core/di/injector.js:828:25)
        at Injector._instantiate (/Users/administrator/go/src/hackman/node_modules/angular2/src/core/di/injector.js:720:36)
        at Injector._instantiateProvider (/Users/administrator/go/src/hackman/node_modules/angular2/src/core/di/injector.js:711:25)
        at Injector._new (/Users/administrator/go/src/hackman/node_modules/angular2/src/core/di/injector.js:700:21)
        at InjectorInlineStrategy.instantiateProvider (/Users/administrator/go/src/hackman/node_modules/angular2/src/core/di/injector.js:197:30)
        at ElementInjectorInlineStrategy.hydrate (/Users/administrator/go/src/hackman/node_modules/angular2/src/core/linker/element_injector.js:650:24)
        at ElementInjector.hydrate (/Users/administrator/go/src/hackman/node_modules/angular2/src/core/linker/element_injector.js:311:24)
        at AppViewManagerUtils._hydrateView (/Users/administrator/go/src/hackman/node_modules/angular2/src/core/linker/view_manager_utils.js:177:41)
        at AppViewManagerUtils.hydrateRootHostView (/Users/administrator/go/src/hackman/node_modules/angular2/src/core/linker/view_manager_utils.js:104:14)
        at AppViewManager_.createRootHostView (/Users/administrator/go/src/hackman/node_modules/angular2/src/core/linker/view_manager.js:111:21)
        at /Users/administrator/go/src/hackman/node_modules/angular2/src/core/linker/dynamic_component_loader.js:102:50
        at Zone.run (/Users/administrator/go/src/hackman/node_modules/zone.js/dist/zone-microtask.js:120:17)
        at zoneBoundFn (/Users/administrator/go/src/hackman/node_modules/zone.js/dist/zone-microtask.js:93:19)
        at lib$es6$promise$$internal$$tryCatch (/Users/administrator/go/src/hackman/node_modules/zone.js/dist/zone-microtask.js:1489:16)
        at lib$es6$promise$$internal$$invokeCallback (/Users/administrator/go/src/hackman/node_modules/zone.js/dist/zone-microtask.js:1501:17)
        at lib$es6$promise$$internal$$publish (/Users/administrator/go/src/hackman/node_modules/zone.js/dist/zone-microtask.js:1472:11)
        at /Users/administrator/go/src/hackman/node_modules/zone.js/dist/zone-microtask.js:201:5
        at Zone.run (/Users/administrator/go/src/hackman/node_modules/zone.js/dist/zone-microtask.js:120:17)
        at zoneBoundFn (/Users/administrator/go/src/hackman/node_modules/zone.js/dist/zone-microtask.js:93:19)
        at MutationObserver.lib$es6$promise$asap$$flush (/Users/administrator/go/src/hackman/node_modules/zone.js/dist/zone-microtask.js:1283:9)

[23:20:57] 'karma.start' errored after 4.4 s
[23:20:57] Error: 1
    at formatError (/Users/administrator/go/src/hackman/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/Users/administrator/go/src/hackman/node_modules/gulp/bin/gulp.js:195:15)
    at emitOne (events.js:82:20)
    at Gulp.emit (events.js:169:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/administrator/go/src/hackman/node_modules/orchestrator/index.js:264:8)
    at /Users/administrator/go/src/hackman/node_modules/orchestrator/index.js:275:23
    at finish (/Users/administrator/go/src/hackman/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/administrator/go/src/hackman/node_modules/orchestrator/lib/runTask.js:29:3)
    at removeAllListeners (/Users/administrator/go/src/hackman/node_modules/karma/lib/server.js:215:7)
    at Server.<anonymous> (/Users/administrator/go/src/hackman/node_modules/karma/lib/server.js:226:9)
[23:20:57] 'test' errored after 7.63 s
[23:20:57] Error in plugin 'run-sequence'
Message:
    An error occured in task 'karma.start'.
npm ERR! Test failed.  See above for more details.
```

How should I fix the DI to make testing this pass?

**Comment by ludohenin** [comment]
@johnjelinek You have to declare your providers :)
```
@Component({selector: 'test-cmp', providers: [PostList]})
@View({directives: [HomeCmp]})
class TestComponent {}
```
-> Note the `providers` property added to `TestCmp` of `home_spec.ts`.

**Comment by johnjelinek** [comment]
Interesting, I use `viewProviders` in `app.ts`, but `providers` in the test for `home_spect.ts`. Why? It passes now, thanks.

**Comment by ludohenin** [comment]
`viewProviders` should work in `home_spect.ts ` as well.
The difference between both is just the scope the providers are accessible from (if not wrong).
