### ISSUE TITLE
[Question] 'system' module code generation type not supported?

### ISSUE THREAD

**Issue by david-lee** [mgechev/angular2-seed#337]
After I cloned and run `npm install`, I changed module code generation option in `tsconfig.json`. It was `commonjs` and changed to `system`. And I got an error like below as run `npm start`

```
import * as gulp from 'gulp';
^
ReferenceError: System is not defined
    at Object.<anonymous> (D:\devs\ng2\angular2-seed\gulpfile.ts:1:1)
    at Module._compile (module.js:435:26)
    at Object.loader (D:\devs\ng2\angular2-seed\node_modules\ts-node\src\ts-node.ts:225:14)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Liftoff.handleArguments (D:\devs\ng2\angular2-seed\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (D:\devs\ng2\angular2-seed\node_modules\gulp\node_modules\liftoff\index.js:192:16)
    at module.exports (D:\devs\ng2\angular2-seed\node_modules\gulp\node_modules\liftoff\node_modules\flagged-respawn\index.js:17:3)
```
 Doesn't this seed project support 'system' module code generation?

Thanks.

**Comment by mgechev** [comment]
At this point we use a single `tsconfig.json` file which is used by both:
- `ts-node` for executing the `gulpfile.ts` and the related tasks.
- compilation of the application itself

You can compile the application to systemjs by changing the ts project configuration at: `./tools/utils.ts`:
```ts
...
export function tsProjectFn(plugins) {
  return plugins.typescript.createProject('tsconfig.json', {
    typescript: require('typescript'),
    module: 'system'
  });
}
```

**Comment by david-lee** [comment]
Great! It works for me. Thanks.

**Comment by h4ckm03d** [comment]
I'm encountered same problem with same condition but still show the error like above.
```
[20:58:17] Requiring external module ts-node/register

/home/upi/dev/gopath/src/cloudnfc/gulpfile.ts:1
import * as gulp from 'gulp';
^
ReferenceError: System is not defined
    at Object.<anonymous> (/home/upi/dev/gopath/src/cloudnfc/gulpfile.ts:1:1)
    at Module._compile (module.js:435:26)
    at Object.loader (/home/upi/dev/gopath/src/cloudnfc/node_modules/ts-node/src/ts-node.ts:225:14)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Liftoff.handleArguments (/home/upi/.nvm/versions/node/v4.2.1/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/home/upi/.nvm/versions/node/v4.2.1/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/home/upi/.nvm/versions/node/v4.2.1/lib/node_modules/gulp/node_modules/flagged-respawn/index.js:17:3)
```
Files `./tools/utils.ts` already updated using `module:'system'`
Any suggestion? .
