### ISSUE TITLE
e2e tests and sourceMap

### ISSUE THREAD

**Issue by pjpsoares** [mgechev/angular2-seed#365]
Hi!
I've just cloned this repo, and followed all the instructions to run the e2e tests and I get this error:
```
Message:
    TypeError: Column must be greater than or equal to 0, got -62
  Stack:
    TypeError: Column must be greater than or equal to 0, got -62
        at SourceMapConsumer_findMapping [as _findMapping] (/Users/paulo/depot/personal/angular2-seed/node_modules/source-map-support/node_modules/source-map/lib/source-map/source-map-consumer.js:281:15)
        at SourceMapConsumer_originalPositionFor [as originalPositionFor] (/Users/paulo/depot/personal/angular2-seed/node_modules/source-map-support/node_modules/source-map/lib/source-map/source-map-consumer.js:310:26)
        at mapSourcePosition (/Users/paulo/depot/personal/angular2-seed/node_modules/source-map-support/source-map-support.js:168:42)
        at wrapCallSite (/Users/paulo/depot/personal/angular2-seed/node_modules/source-map-support/source-map-support.js:303:20)
        at /Users/paulo/depot/personal/angular2-seed/node_modules/source-map-support/source-map-support.js:338:26
        at Array.map (native)
        at Function.prepareStackTrace (/Users/paulo/depot/personal/angular2-seed/node_modules/source-map-support/source-map-support.js:337:24)
        at Suite.<anonymous> (/source/components/home/home.e2e.ts:3:3)
        at addSpecsToSuite (/Users/paulo/depot/personal/angular2-seed/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:743:25)
```

**Comment by mgechev** [comment]
@NathanWalker would you take a look at this one?

**Comment by pjpsoares** [comment]
Just to add a little more info, just tried in my colleague computer and it works fine. If you have any clue on what might be going on would be great.

**Comment by mgechev** [comment]
What are your OS, node, npm, Chrome (I guess you're using protractor with Chrome?) versions?

**Comment by pjpsoares** [comment]
OS: osx el capitan 10.11.12
node: v5.2.0
npm: 3.3.12
chrome: 47.0.2526.106 (64-bit)

**Comment by NathanWalker** [comment]
@pjpsoares If it's isolated to just your computer and works fine on your colleagues, what are the OS, node, npm, Chrome versions on your colleagues computer?
Also is the install path of node the same between yours and your colleagues?

**Comment by pjpsoares** [comment]
Same OS, node v4.2.1, npm 2.14.7.
Same install path.

**Comment by pjpsoares** [comment]
Downgrading node does the trick...

**Comment by NathanWalker** [comment]
Ah ok, good to know. I've had issues in general with node 5.x as well. I've been sticking with 4.2.1 and it's been smooth sailing with all things node.
