### ISSUE TITLE
Hot loader in Windows (solved)

### ISSUE THREAD

**Issue by jmfvarela** [mgechev/angular2-seed#368]
I have found that changing line 14 in:
    https://github.com/mgechev/angular2-seed/blob/master/tools/utils/code_change_tools.ts
this:
```javascript
return file.replace(`${PROJECT_ROOT}${sep}${APP_SRC}`, '/dist/dev/');`
```
for this:
```javascript
return file.replace(`${PROJECT_ROOT}${sep}${APP_SRC}`, '/dist/dev').replace(/\\/g, '/');
```
it works.
Sorry because that solution is not very orthodox. ;-)

**Comment by mgechev** [comment]
Great! Thanks for the solution. I will update the code according the changes tou suggest tomorrow.

**Comment by mgechev** [comment]
@jmfvarela would you verify it works with the changes introduced by https://github.com/mgechev/angular2-seed/commit/5fbf14429ae7e1ed8a79a7928f9821a20b1c9418.

**Comment by jmfvarela** [comment]
Hi @mgechev. I've verified it, but the installation proccess (npm install) doesn't work on Windows. Perhaps is my problem. I´m goig to check it when I have a chance...

```
C:\backup\personal projects\temp>npm install

> bufferutil@1.2.1 install C:\backup\personal projects\temp\node_modules\bufferu
til
> node-gyp rebuild


C:\backup\personal projects\temp\node_modules\bufferutil>if not defined npm_conf
ig_node_gyp (node "C:\Users\jfernanv\AppData\Roaming\npm\node_modules\npm\bin\no
de-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node
rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Python executable "C:\Python34\python.EXE" is v3.4.4, whic
h is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & <
 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Users\jfernanv\AppData\Roaming\npm\n
ode_modules\npm\node_modules\node-gyp\lib\configure.js:406:14)
gyp ERR! stack     at C:\Users\jfernanv\AppData\Roaming\npm\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:395:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp ERR! stack     at Pipe._onclose (net.js:469:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\jfernan
v\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-g
yp.js" "rebuild"
gyp ERR! cwd C:\backup\personal projects\temp\node_modules\bufferutil
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
npm WARN install:bufferutil@1.2.1 Exit status 1

> utf-8-validate@1.2.1 install C:\backup\personal projects\temp\node_modules\utf
-8-validate
> node-gyp rebuild


C:\backup\personal projects\temp\node_modules\utf-8-validate>if not defined npm_
config_node_gyp (node "C:\Users\jfernanv\AppData\Roaming\npm\node_modules\npm\bi
n\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (no
de  rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Python executable "C:\Python34\python.EXE" is v3.4.4, whic
h is not supported by gyp.
gyp ERR! stack You can pass the --python switch to point to Python >= v2.5.0 & <
 3.0.0.
gyp ERR! stack     at failPythonVersion (C:\Users\jfernanv\AppData\Roaming\npm\n
ode_modules\npm\node_modules\node-gyp\lib\configure.js:406:14)
gyp ERR! stack     at C:\Users\jfernanv\AppData\Roaming\npm\node_modules\npm\nod
e_modules\node-gyp\lib\configure.js:395:9
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:204:7)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at maybeClose (internal/child_process.js:818:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:319:11)
gyp ERR! stack     at emitOne (events.js:77:13)
gyp ERR! stack     at Socket.emit (events.js:169:7)
gyp ERR! stack     at Pipe._onclose (net.js:469:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files (x86)\\nodejs\\node.exe" "C:\\Users\\jfernan
v\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-g
yp.js" "rebuild"
gyp ERR! cwd C:\backup\personal projects\temp\node_modules\utf-8-validate
gyp ERR! node -v v4.2.4
gyp ERR! node-gyp -v v3.2.1
gyp ERR! not ok
npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp re
build`
npm WARN install:utf-8-validate@1.2.1 Exit status 1

> angular2-seed@0.0.0 postinstall C:\backup\personal projects\temp
> tsd reinstall --clean && tsd link && tsd rebundle && gulp check.versions && gu
lp postinstall


-> running reinstall

>> written zero files

   >> definition-header (node)
   >> reflect-metadata (node)

>> nothing rebundled
[14:11:07] Requiring external module ts-node/register
[14:11:12] Loading task clean all
[14:11:13] Loading task clean dist
[14:11:13] Loading task clean test
[14:11:13] Loading task clean tmp
[14:11:13] Loading task check.versions
[14:11:14] Using gulpfile C:\backup\personal projects\temp\gulpfile.ts
[14:11:14] Starting 'check.versions'...
[14:11:14] Finished 'check.versions' after 31 ms
[14:11:15] Requiring external module ts-node/register
[14:11:21] Loading task clean all
[14:11:21] Loading task clean dist
[14:11:21] Loading task clean test
[14:11:21] Loading task clean tmp
[14:11:21] Loading task check.versions
[14:11:22] Using gulpfile C:\backup\personal projects\temp\gulpfile.ts
[14:11:22] Starting 'postinstall'...
[14:11:22] Loading task clean
[14:11:22] Loading task npm
[14:11:23] Starting 'clean'...
[14:11:23] Finished 'clean' after 103 µs
[14:11:23] Starting 'npm'...
[14:11:25] Finished 'npm' after 2.39 s
[14:11:25] Finished 'postinstall' after 3.07 s
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.6

```

**Comment by jmfvarela** [comment]
It seems to be my version of Python, required by gyp...

**Comment by Bigous** [comment]
Yes... it needs python 2.7 ...

**Comment by jmfvarela** [comment]
OK
Also node-gyp needs Microsoft Visual Studio C++ 2013 in Windows (https://github.com/nodejs/node-gyp).
Do you know why it is needed node-gyp for angular-seed?

**Comment by mgechev** [comment]
@jmfvarela I guess any of the dependencies uses it, may be indirectly.
