### ISSUE TITLE
IE10 & IE11 Syntax Error: The use of a keyword for an identifier is invalid

### ISSUE THREAD

**Issue by jimulle** [mgechev/angular2-seed#376]
When I clone the seed project and try to view it in IE10, I get the following error:
> EXCEPTION: SyntaxError: The use of a keyword for an identifier is invalid 

Unfortunately, the console output is rather cryptic and isn't providing me with much insight into the cause of this issue.

*Full Console Output:*
> SyntaxError: The use of a keyword for an identifier is invalid
   at T (http://localhost:5555/node_modules/angular2/bundles/angular2.min.js:1:1792)
   at e.prototype._createViewFactoryRuntime (http://localhost:5555/node_modules/angular2/bundles/angular2.min.js:18:4319)
   at Anonymous function (http://localhost:5555/node_modules/angular2/bundles/angular2.min.js:18:2971)
   at run (http://localhost:5555/node_modules/angular2/bundles/angular2-polyfills.js:138:7)
   at Anonymous function (http://localhost:5555/node_modules/angular2/bundles/angular2.min.js:10:9636)
   at zoneBoundFn (http://localhost:5555/node_modules/angular2/bundles/angular2-polyfills.js:111:7)
   at lib$es6$promise$$internal$$tryCatch (http://localhost:5555/node_modules/angular2/bundles/angular2-polyfills.js:1511:9)
   at lib$es6$promise$$internal$$invokeCallback (http://localhost:5555/node_modules/angular2/bundles/angular2-polyfills.js:1523:9)
   at Anonymous function (http://localhost:5555/node_modules/angular2/bundles/angular2-polyfills.js:

**Comment by jimulle** [comment]
As additional clarification, this error starts after this commit
> Update to beta.1 
> 5ecfd19f2d8baacb22cc7ac907cceb4aa237d313

**Comment by mgechev** [comment]
As workaround for now you can use the code under this tag https://github.com/mgechev/angular2-seed/tree/2.0.0-beta.0

**Comment by jimulle** [comment]
Thanks. I actually rolled back to this commit (Merge pull request #371 from mgechev/fix-333 0a23a0398c8a762530d269a22ab28ce42a9735fc) and it works for now. I'll keep an eye out for a resolution to the issue (maybe in 2.0.0-beta.2)

**Comment by mgechev** [comment]
This is weird. https://github.com/mgechev/angular2-seed/pull/371 contains only changes in the component's spec.

Would you test against master again? I removed the explicit use of `CORE_DIRECTIVES` from the `AboutCmp`. May be there was name collision or something like that when the same directives are included twice.

**Comment by jimulle** [comment]
That commit works fine, it is the change to 2.0.0-beta.1 that breaks it.

**Comment by mgechev** [comment]
Ah, yes. Just saw your comment.

**Comment by mgechev** [comment]
Lets close this issue since it is not related to the seed but to angular2 beta.1 instead.
