### ISSUE TITLE
TypeError: Object doesn't support property or method 'keys' 

### ISSUE THREAD

**Issue by andycwk** [mgechev/angular2-seed#381]
Hi,

I'm using Angular 2.0.0-beta.1 and have the following exception in Internet Explorer 11 (think it also shows in 9 & 10 too but with less info)

```
TypeError: Object doesn't support property or method 'keys'
   at Anonymous function (http://localhost:5000/app/angular2.dev.js:783:5)
   at Anonymous function (http://localhost:5000/app/angular2.dev.js:781:3)
   at linkDynamicModule (https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.16/system.src.js:3130:5)
   at getModule (https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.16/system.src.js:3098:9)
   at Anonymous function (https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.16/system.src.js:3134:9)
   at Anonymous function (http://localhost:5000/app/angular2.dev.js:10795:3)
   at linkDynamicModule (https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.16/system.src.js:3130:5)
   at getModule (https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.16/system.src.js:3098:9)
   at Anonymous function (https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.16/system.src.js:3134:9)
   at Anonymous function (http://localhost:5000/app/angular2.dev.js:12011:3) 
```

The start of my index.html looks like the following at the moment..
```
<head>
    <title ng-bind="title">xxx</title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge, chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1, user-scalable=no" />
    <base href="/">

    <link rel="stylesheet" href="/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="/css/style.css" />
    <link rel="stylesheet" href="/css/main.css" />

    <script src="https://cdnjs.cloudflare.com/ajax/libs/es5-shim/4.4.1/es5-sham.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/es6-shim/0.34.1/es6-sham.min.js"></script>
    <script src="https://code.angularjs.org/2.0.0-beta.1/angular2-polyfills.js"></script>
    
    <script src="https://code.angularjs.org/tools/typescript.js"></script>

    <script src="/app/reflect.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.16/system.src.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/systemjs/0.19.16/system-polyfills.src.js"></script>
    <script src="https://code.angularjs.org/2.0.0-beta.1/Rx.js"></script>
    <!--<script src="https://code.angularjs.org/2.0.0-beta.1/angular2.dev.js"></script>-->
    <script src="/app/angular2.dev.js"></script>

    <script src="/app/shims_for_IE.js"></script>

    <script>
        System.config({
        packages: {        
          app: {
            format: 'register',
            defaultExtension: 'js'
          }
        }
      });
      System.import('app/boot')
            .then(function(){
            }, function(err){
                console.log(err.stack);
            });
    </script>
</head>
```

As you can see, I've thrown all sorts into the mix to try and resolve the issue!

Any thoughts... is it a bug? Am I missing something obvious?

**Comment by mgechev** [comment]
@andycwk looking at the setup of your `index.html`, this doesn't seems like an issue related to this project. May me more appropriate place to report is https://github.com/angular/angular/issues.

**Comment by andycwk** [comment]
Ah bugger.. didn't realise I was posting against the seed project - this is what happens when logging an issue @ 12 am :(

Sorry :(

**Comment by mgechev** [comment]
@andycwk no worries!
