### ISSUE TITLE
Error on npm run build.prod in newly cloned repo

### ISSUE THREAD

**Issue by e-oz** [mgechev/angular2-seed#539]
I just cloned fresh version of repo, npm install was fine, then `npm run build.prod` failed:

```
[16:05:19] 'build.assets.prod' errored after 2.37 ms
[16:05:19] TypeError: Path must be a string. Received [ { src: 'src/assets/main.css', inject: true } ]
    at assertPath (path.js:8:11)
    at Object.posix.join (path.js:479:5)
    at Gulp.<anonymous> (.../tools/tasks/build.assets.prod.ts:22:15)
```

**Comment by mgechev** [comment]
Probably related with this https://github.com/mgechev/angular2-seed/pull/536.

Should be fixed soon.

**Comment by ludohenin** [comment]
fix by abb67a5

**Comment by e-oz** [comment]
thanks. now it works... although result is quite shocking... instead of 1 js and 1 css file I see a lot of folders and I see I can't change src folders structure......

**Comment by e-oz** [comment]
nevermind, folders structure change was possible, and looks like all of these files in prod are copied not to load them later.
