### ISSUE TITLE
build.index.dev is failing with an undefined function error

### ISSUE THREAD

**Issue by micahblu** [mgechev/angular2-seed#566]
This is the error I receive after entering `npm start`

```
[21:59:09] 'build.index.dev' errored after 335 ms
[21:59:09] TypeError: undefined is not a function
    at mapPath (/Users/computer/Projects/angular2-seed/tools/tasks/build.index.dev.ts:32:17)
    at Array.map (native)
    at getInjectablesDependenciesRef (/Users/computer/Projects/angular2-seed/tools/tasks/build.index.dev.ts:27:8)
    at inject (/Users/computer/Projects/angular2-seed/tools/tasks/build.index.dev.ts:18:36)
    at Gulp.<anonymous> (/Users/computer/Projects/angular2-seed/tools/tasks/build.index.dev.ts:9:13)
    at module.exports (/Users/computer/Projects/angular2-seed/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/computer/Projects/angular2-seed/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/computer/Projects/angular2-seed/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/computer/Projects/angular2-seed/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/Users/computer/Projects/angular2-seed/node_modules/run-sequence/index.js:88:16)
[21:59:09] 'serve.dev' errored after 55 s
[21:59:09] Error in plugin 'run-sequence'
Message:
    An error occured in task 'build.index.dev'.
[21:59:09] 'build.dev' errored after 49 s
[21:59:09] Error in plugin 'run-sequence'
Message:
    An error occured in task 'serve.dev'.
[21:59:09] 'build.dev' errored after 49 s
[21:59:09] Error in plugin 'run-sequence'
Message:
    An error occured in task 'build.index.dev'.
```

**Comment by mgechev** [comment]
Would you provide the output of:

```bash
tsc --v
```

**Comment by micahblu** [comment]
Version 1.8.7

**Comment by ludohenin** [comment]
@micahblu I'd say you're not using the right `node` version. We start support from 4+

**Comment by micahblu** [comment]
That was it! Thanks much for the prompt help :)
