### ISSUE TITLE
ng2lint rules in tslint.json makes VS code not able to run tslint

### ISSUE THREAD

**Issue by allenhwkim** [mgechev/angular2-seed#582]
This commits in tslint.json makes VS code, which is a popular NG2 editor, not able to run tslint.

IMHO, it's not a good idea to write tslint rules and ng2lint rules together in the same file.

093db587224ed686cd7e85774b3e08213a83c236
0e8f503a5d514b04eba71ac9fcef58681d94924b

With ng2lint rules in tslint.json

![image](https://cloud.githubusercontent.com/assets/1437734/13551255/566c31ea-e301-11e5-9f4c-ac6683d4a043.png)

Without ng2lint rules in tslint.json
![image](https://cloud.githubusercontent.com/assets/1437734/13551266/7d93e16e-e301-11e5-9ab0-8a41b77a943b.png)

**Comment by d3viant0ne** [comment]
@allenhwkim - Attaching error output would probably be helpful.

**Comment by allenhwkim** [comment]
Output from console

```
angular2-seed (master)$ git remote show origin
* remote origin
  Fetch URL: https://github.com/allenhwkim/angular2-seed.git
...
...
angular2-seed (master)$ tslint src/home/components/home.component.ts*
/Users/allen/.nvm/versions/node/v0.12.7/lib/node_modules/tslint/lib/ruleLoader.js:29
        throw new Error(errorMessage);
              ^
Error: Could not find the following rules specified in the configuration:
component-selector-name
component-selector-type
host-parameter-decorator
input-parameter-decorator
output-parameter-decorator
attribute-parameter-decorator
input-property-directive
output-property-directive
    at Object.loadRules (/Users/allen/.nvm/versions/node/v0.12.7/lib/node_modules/tslint/lib/ruleLoader.js:29:15)
    at Linter.lint (/Users/allen/.nvm/versions/node/v0.12.7/lib/node_modules/tslint/lib/tslint.js:24:44)
    at processFile (/Users/allen/.nvm/versions/node/v0.12.7/lib/node_modules/tslint/lib/tslint-cli.js:115:29)
    at Array.forEach (native)
    at Object.<anonymous> (/Users/allen/.nvm/versions/node/v0.12.7/lib/node_modules/tslint/lib/tslint-cli.js:125:21)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
```

**Comment by d3viant0ne** [comment]
@allenhwkim  The seed requires an NPM version greater than 4.x
