### ISSUE TITLE
Gulp serve slower on windows

### ISSUE THREAD

**Issue by sfabriece** [mgechev/angular2-seed#700]
I had a chance to try my project on a mac today. Gulp serve.dev is way faster on the mac compared to the windows counterpart.

Both the mac and windows are ssd based.

Is there a reason this is, or Am I the only one experiencing this.

PS: not sure according to guidelines if this is a support problem or a bug. Please enlighten so as to prevent future confusion. Where should support issues be posted?

**Comment by mgechev** [comment]
@sfabriece slow in what sense? After you save your file it takes more time until your browser refreshes or you mean anything else?

The problem could be related to:

- Slow detection in changed files (using `gulp-watch`).
- Slow TypeScript transpilation (we're using TypeScript's compiler)

**Comment by sfabriece** [comment]
@mgechev 
 I collected some stats on both systems. 3 times for windows 2 for mac
i'll give the minimum values of the # of tries.

for windows:
```
registering external modules  42 seconds
tslint 5.68 seconds
build.html_css 3.72 seconds
build.js.dev 6.48 seconds
build.dev 23 seconds
serve.dev 28 seconds
```
for Mac
```
registering external modules  2 seconds
tslint 1.46 seconds
build.html_css 449 ms
build.js.dev 2.28 seconds
build.dev 4.3 seconds
serve.dev 4.36 seconds
```

**Comment by Toktik** [comment]
Same reason as #699 

It is because of ts-node upgrade. 0.5.5 was OK.

**Comment by sfabriece** [comment]
found that issue, I tried downgrading to 0.5.5 with no significant change in performance.

**Comment by d3viant0ne** [comment]
@sfabriece - For reference, node in general is slower on windows ( it's better with 5.9 but still slower ).

Timings aside, i'm curious about the specs of both systems.

CPU / Memory / Hard Disk types

**Comment by mgechev** [comment]
Today I dug into this issue, it is caused by `ts-node` (or even in the compiler in case files are added incrementally). What we can do is:

- Precompile the tools directory to JavaScript using `tsc --project tsconfig.json` in the root of the project. In tools add `.gitignore` with content `*.js`.
- Bundle all files into a single one in order to reduce the calls for requiring `ts` files, and respectively compiling them.

// cc @blakeembrey

**Comment by mgechev** [comment]
Here's a temporal solution which speeds the build up dramatically https://github.com/mgechev/angular2-seed/wiki/Speedup-the-build-on-Windows

**Comment by blakeembrey** [comment]
@mgechev Did you find this was just an issue with speed on Windows? That's really concerning. Aside from that, I'd consider not using `ts-node` until a straight transpile mode exists because type checking is really the expensive part here. It's a real PITA, because the reason I want `ts-node` to exist is the opposite end of the spectrum to others :smile:

**Comment by mgechev** [comment]
@blakeembrey yes, only Windows issue on Mac/Linux everything works perfectly.

**Comment by mattisebastian** [comment]
currently this breaks the build on windows:

```
[19:12:47] Using gulpfile ~\graphicuss-angular\gulpfile.js
[19:12:47] Starting 'serve.dev'...
[19:12:47] Starting 'build.dev'...
[19:12:47] Starting 'initialize'...
[19:12:48] Starting 'noop'...
[19:12:48] 'noop' errored after 611 μs
[19:12:48] Error: Cannot find module '\graphicuss-angular\tools\tasks\seed\noop'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Gulp.<anonymous> (graphicuss-angular\tools\utils\seed\tasks_tools.js:113:34)
    at module.exports (\graphicuss-angular\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (graphicuss-angular\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (graphicuss-angular\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (graphicuss-angular\node_modules\orchestrator\index.js:134:8)
    at runNextSet (graphicuss-angular\node_modules\run-sequence\index.js:123:15)
[19:12:48] 'serve.dev' errored after 67 ms
[19:12:48] Error in plugin 'run-sequence(noop)'
Message:
    Cannot find module 'graphicuss-angular\tools\tasks\seed\noop'
Details:
    code: MODULE_NOT_FOUND
Stack:
Error: Cannot find module 'graphicuss-angular\tools\tasks\seed\noop'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Gulp.<anonymous> (graphicuss-angular\tools\utils\seed\tasks_tools.js:113:34)
    at module.exports (graphicuss-angular\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (graphicuss-angular\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (graphicuss-angular\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (graphicuss-angular\node_modules\orchestrator\index.js:134:8)
    at runNextSet (graphicuss-angular\node_modules\run-sequence\index.js:123:15)
[19:12:48] 'build.dev' errored after 120 ms
[19:12:48] Error in plugin 'run-sequence(serve.dev)'
```
this goes on for 'initialize'. Any ideas how to fix this?
