### ISSUE TITLE
Typescript Compilation errors on updating to latest version.

### ISSUE THREAD

**Issue by kambojankit** [mgechev/angular2-seed#710]
Hey 

I updated my project to the latest version of the seed (from seed's release version 2.0.0-beta.2), to be inline with updates to tools and configuration changes.
But now i have a lot of breaking typescript errors during `npm install`.
I tried to change the ts-lint settings and ts-config settings to their previous state, but that also didn't resolve the issue. 

> Note: These typescript errors/warning are present in my project, but were not breaking the build earlier. 

Below is the error sample: 
```
[20:21:36] Requiring external module ts-node/register
TSError: ? Unable to compile TypeScript
src\common\entity\component\entity-widget.component.ts (30,20): Property 'modal' does not exist on type 'ElementFinder'. (2339)
src\common\entity\component\entity-widget.component.ts (33,26): Property 'modal' does not exist on type 'ElementFinder'. (2339)
src\common\entity\component\entity-widget.component.ts (37,20): Property 'modal' does not exist on type 'ElementFinder'. (2339)
src\common\entity\component\entity-widget.component.ts (42,22): Property 'modal' does not exist on type 'ElementFinder'. (2339)
typings\main\ambient\Q\Q.d.ts (24,9): Duplicate identifier 'promise'. (2300)
typings\main\ambient\Q\Q.d.ts (168,9): Duplicate identifier 'state'. (2300)
typings\main\ambient\Q\Q.d.ts (169,9): Duplicate identifier 'value'. (2300)
typings\main\ambient\Q\Q.d.ts (170,9): Duplicate identifier 'reason'. (2300)
typings\main\ambient\Q\Q.d.ts (336,5): Duplicate identifier 'export='. (2300)
typings\main\ambient\Q\index.d.ts (24,9): Duplicate identifier 'promise'. (2300)
typings\main\ambient\Q\index.d.ts (168,9): Duplicate identifier 'state'. (2300)
typings\main\ambient\Q\index.d.ts (169,9): Duplicate identifier 'value'. (2300)
typings\main\ambient\Q\index.d.ts (170,9): Duplicate identifier 'reason'. (2300)
typings\main\ambient\Q\index.d.ts (336,5): Duplicate identifier 'export='. (2300)
.
.
.
typings\main\definitions\xhr2\xhr2.d.ts (170,1): Duplicate identifier 'export='. (2300)
    at getOutput (C:\****\***\angular2\**frontend\node_modules\ts-node\src\ts-node.ts:209:13)
    at Object.loader (C:\****\***\angular2\**frontend\node_modules\ts-node\src\ts-node.ts:224:23)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Liftoff.handleArguments (C:\****\***\angular2\**frontend\node_modules\gulp\bin\gulp.js:116:3)
    at Liftoff.<anonymous> (C:\****\***\angular2\**frontend\node_modules\liftoff\index.js:192:16)
    at module.exports (C:\****\***\angular2\**frontend\node_modules\flagged-respawn\index.js:17:3)
    at Liftoff.<anonymous> (C:\****\***\angular2\**frontend\node_modules\liftoff\index.js:185:9)
```

**Comment by mgechev** [comment]
Hey @kambojankit here's what cases the problem and [how it can be fixed](http://blog.mgechev.com/2016/03/28/ambient-type-definitions-duplicate-identifier-typescript-fix/).
