### ISSUE TITLE
gulp cannot find module on windows 10

### ISSUE THREAD

**Issue by OlivierMary** [mgechev/angular2-seed#711]
Hi,

I checkout the project yesterday, and I have the following problem only on my windows 10, 0 problem on ubuntu with same npm/node versions.

The problem : 
```

PS C:\repositories\angular2-seed> npm install

> angular2-seed@0.0.0 postinstall C:\repositories\angular2-seed
> typings install && gulp check.versions && npm prune


├── xhr2
├── Q (ambient)
├── angular-protractor (ambient)
├── async (ambient)
├── browser-sync (ambient)
├── chalk (ambient)
├── chokidar (ambient)
├── es6-shim (ambient)
├── express (ambient)
├── glob (ambient)
├── gulp (ambient)
├── gulp-load-plugins (ambient)
├── gulp-shell (ambient)
├── gulp-util (ambient)
├── jasmine (ambient)
├── micromatch (ambient)
├── mime (ambient)
├── minimatch (ambient)
├── ng2 (ambient)
├── node (ambient)
├── orchestrator (ambient)
├── parse-glob (ambient)
├── rimraf (ambient)
├── run-sequence (ambient)
├── selenium-webdriver (ambient)
├── serve-static (ambient)
├── systemjs (ambient)
├── through2 (ambient)
├── vinyl (ambient)
├── vinyl-source-stream (ambient)
├── yargs (ambient)
└── zone.js (ambient)

[14:09:33] Loading tasks folder C:\repositories\angular2-seed\tools\tasks\seed
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\build.assets.dev
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\build.assets.prod
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\build.bundles.app
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\build.bundles
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\build.docs
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\build.html_css
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\build.index.dev
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\build.index.prod
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\build.js.dev
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\build.js.e2e
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\build.js.prod
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\build.js.test
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\build.js.tools
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\check.versions
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\clean.all
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\clean.dev
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\clean.prod
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\clean.tools
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\copy.js.prod
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\css-lint
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\karma.start
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\serve.coverage
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\serve.docs
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\server.prod
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\server.start
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\tslint
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\watch.dev
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\watch.e2e
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\seed\watch.test
[14:09:33] Loading tasks folder C:\repositories\angular2-seed\tools\tasks\project
[14:09:33] Registering task C:\repositories\angular2-seed\tools\tasks\project\sample.task
[14:09:33] Using gulpfile C:\repositories\angular2-seed\gulpfile.js
[14:09:33] Starting 'check.versions'...
[14:09:33] 'check.versions' errored after 253 μs
[14:09:33] Error: Cannot find module 'C:\repositories\angular2-seed\tools\tasks\seed\check.versions'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Gulp.<anonymous> (C:\repositories\angular2-seed\tools\utils\seed\tasks_tools.js:16:20)
    at module.exports (C:\repositories\angular2-seed\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\repositories\angular2-seed\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\repositories\angular2-seed\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\repositories\angular2-seed\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at C:\Users\olivi\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm WARN optional Skipping failed optional dependency /gulp-watch/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm WARN optional Skipping failed optional dependency /karma/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.11
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.3
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 postinstall: `typings install && gulp check.versions && npm prune`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed@0.0.0 postinstall script 'typings install && gulp check.versions && npm prune'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     typings install && gulp check.versions && npm prune
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\repositories\angular2-seed\npm-debug.log
PS C:\repositories\angular2-seed>

```

It's the same problem for all tasks like :

```
PS C:\repositories\angular2-seed> gulp sample.task
[14:15:01] Loading tasks folder C:\repositories\angular2-seed\tools\tasks\seed
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\build.assets.dev
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\build.assets.prod
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\build.bundles.app
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\build.bundles
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\build.docs
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\build.html_css
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\build.index.dev
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\build.index.prod
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\build.js.dev
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\build.js.e2e
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\build.js.prod
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\build.js.test
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\build.js.tools
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\check.versions
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\clean.all
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\clean.dev
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\clean.prod
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\clean.tools
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\copy.js.prod
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\css-lint
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\karma.start
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\serve.coverage
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\serve.docs
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\server.prod
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\server.start
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\tslint
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\watch.dev
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\watch.e2e
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\seed\watch.test
[14:15:01] Loading tasks folder C:\repositories\angular2-seed\tools\tasks\project
[14:15:01] Registering task C:\repositories\angular2-seed\tools\tasks\project\sample.task
[14:15:01] Using gulpfile C:\repositories\angular2-seed\gulpfile.js
[14:15:01] Starting 'sample.task'...
[14:15:01] 'sample.task' errored after 233 μs
[14:15:01] Error: Cannot find module 'C:\repositories\angular2-seed\tools\tasks\project\sample.task'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Gulp.<anonymous> (C:\repositories\angular2-seed\tools\utils\seed\tasks_tools.js:16:20)
    at module.exports (C:\repositories\angular2-seed\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\repositories\angular2-seed\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\repositories\angular2-seed\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\repositories\angular2-seed\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at C:\Users\olivi\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
PS C:\repositories\angular2-seed>
```

`using npm@3.8.3
using node@v5.10.0`

Thanks for your help !

Regards.

**Comment by OlivierMary** [comment]
Hi,

old version of tsc ... with 1.8.9 no problem.

Regards.
