### ISSUE TITLE
[Error] Сannot use Rx Observable in my service

### ISSUE THREAD

**Issue by oneassasin** [mgechev/angular2-seed#753]
Code of my service
```typescript
import {Observable} from 'rxjs';
import {Injectable} from 'angular2/core';

@Injectable()
export class CurrentTimeService {

  private _currentTime:string;

  constructor() {
    Observable.interval(1000)
      .startWith(0)
      .subscribe((time:number) => {
        this._currentTime = new Date().toString();
      });
  }

  get():string {
    return this._currentTime;
  }

}
```
Controller
```typescript
import {Component} from 'angular2/core';
import {CurrentTimeService} from '../../shared/services/current-time.service';

@Component({
  selector: 'sd-toolbar',
  templateUrl: './app/components/toolbar.component.html',
  styleUrls: ['./app/components/toolbar.component.css']
})
export class ToolbarComponent {
  constructor(public currentTimeService:CurrentTimeService) {
  }
}
```
Code of toolbar.component.html
```html
<h1>{{currentTimeService.get()}}</h1>
```
My service was included in app.component
```typescript
@Component({
  selector: 'sd-app',
  viewProviders: [NameListService, CurrentTimeService],
  templateUrl: './app/components/app.component.html',
  directives: [ROUTER_DIRECTIVES, ToolbarComponent]
})
```
Exception in browser
```
Error: SyntaxError: Unexpected token <
	    at Object.eval (http://localhost:5555/node_modules/rxjs/Rx.js:6:17)
	    at eval (http://localhost:5555/node_modules/rxjs/Rx.js:158:4)
	    at eval (http://localhost:5555/node_modules/rxjs/Rx.js:159:3)
	Evaluating http://localhost:5555/node_modules/rxjs/Subject
	Evaluating http://localhost:5555/node_modules/rxjs/Rx.js
	Evaluating http://localhost:5555/shared/services/current-time.service.js
	Evaluating http://localhost:5555/app/components/toolbar.component.js
	Evaluating http://localhost:5555/app/components/app.component.js
	Evaluating http://localhost:5555/main.js
	Error loading http://localhost:5555/main.js "Report this error at https://github.com/mgechev/angular2-seed/issues"(anonymous function) @ localhost/:91
```
Version of used Node.js: 4.4.2
Version of used gulp: 3.9.1
Version of angular2: 2.0.0-beta.14
Version of rxjs: 5.0.0-beta.2

**Comment by mgechev** [comment]
Wrong import. Use:

```ts
import {Observable} from 'rxjs/Observable';
```

**Comment by oneassasin** [comment]
Another error
```
angular2.js?1460552527319:23941 TypeError: Observable_1.Observable.interval is not a function
    at new CurrentTimeService (current-time.service.ts:11)
    at angular2.js?1460552527319:1414
    at Injector._instantiate (angular2.js?1460552527319:11767)
    at Injector._instantiateProvider (angular2.js?1460552527319:11709)
    at Injector._new (angular2.js?1460552527319:11699)
    at InjectorInlineStrategy.getObjByKeyId (angular2.js?1460552527319:11482)
    at Injector._getByKeyDefault (angular2.js?1460552527319:11900)
    at Injector._getByKey (angular2.js?1460552527319:11854)
    at Injector._getByDependency (angular2.js?1460552527319:11842)
    at Injector._instantiate (angular2.js?1460552527319:11737)
```

**Comment by mgechev** [comment]
You have a missing import. Take a look at [the docs](https://angular.io/docs/ts/latest/guide/server-communication.html#!#sts=RxJS%20Library).

**Comment by Arekusei** [comment]
@mgechev Why is this import wrong?
If in systemjs to fix rxjs on a bundle from node_modules this works. At the same time, there is an imported file (module) in rxjs itself.
