### ISSUE TITLE
Issue running 'gulp test' on Mac OS X

### ISSUE THREAD

**Issue by JakePartusch** [mgechev/angular2-seed#78]
Seems to me like the issue might be that `angular2/src/dom` has moved to `angular2/src/core/dom`. Any suggestions?

```bash
[15:09:32] Using gulpfile ~/angular2-testing-workspace/angular2-seed-master/angular2-seed/gulpfile.js
[15:09:32] Starting 'build.test'...
[15:09:33] Finished 'build.test' after 1.43 s
[15:09:33] Starting 'karma.start'...
INFO [karma]: Karma v0.12.37 server started at http://localhost:9876/
INFO [launcher]: Starting browser Chrome
INFO [Chrome 45.0.2454 (Mac OS X 10.10.4)]: Connected on socket AeqoYSodQAdji5r-oG6W with id 68524546
WARN [web-server]: 404: /base/node_modules/angular2/src/dom/browser_adapter.js
Chrome 45.0.2454 (Mac OS X 10.10.4) ERROR: 'Error: XHR error (404 Not Found) loading http://localhost:9876/base/node_modules/angular2/src/dom/browser_adapter.js
    at error (http://localhost:9876/base/node_modules/systemjs/dist/system.src.js?deda5de3b4d843472833379dc10cf66e0aadf1d1:1028:16)
    at XMLHttpRequest.xhr.onreadystatechange [as _onreadystatechange] (http://localhost:9876/base/node_modules/systemjs/dist/system.src.js?deda5de3b4d843472833379dc10cf66e0aadf1d1:1036:13)
    at Zone.run (http://localhost:9876/base/node_modules/angular2/node_modules/zone.js/dist/zone-microtask.js?9d13d72f0e39872af35679eec834b2bdb30db775:118:17)
    at XMLHttpRequest.zoneBoundFn (http://localhost:9876/base/node_modules/angular2/node_modules/zone.js/dist/zone-microtask.js?9d13d72f0e39872af35679eec834b2bdb30db775:91:19)'

Chrome 45.0.2454 (Mac OS X 10.10.4): Executed 0 of 0 ERROR (0.002 secs / 0 secs)
[15:09:35] 'karma.start' errored after 2.21 s
[15:09:35] Error: 1
    at formatError (/usr/local/lib/node_modules/gulp/bin/gulp.js:169:10)
    at Gulp.<anonymous> (/usr/local/lib/node_modules/gulp/bin/gulp.js:195:15)
    at Gulp.emit (events.js:107:17)
    at Gulp.Orchestrator._emitTaskDone (/Users/jakepartusch/angular2-testing-workspace/angular2-seed-master/angular2-seed/node_modules/gulp/node_modules/orchestrator/index.js:264:8)
    at /Users/jakepartusch/angular2-testing-workspace/angular2-seed-master/angular2-seed/node_modules/gulp/node_modules/orchestrator/index.js:275:23
    at finish (/Users/jakepartusch/angular2-testing-workspace/angular2-seed-master/angular2-seed/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/Users/jakepartusch/angular2-testing-workspace/angular2-seed-master/angular2-seed/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:29:3)
    at removeAllListeners (/Users/jakepartusch/angular2-testing-workspace/angular2-seed-master/angular2-seed/node_modules/karma/lib/server.js:215:7)
    at Server.<anonymous> (/Users/jakepartusch/angular2-testing-workspace/angular2-seed-master/angular2-seed/node_modules/karma/lib/server.js:226:9)
    at Server.g (events.js:199:16)
```

**Comment by ludohenin** [comment]
Fixed by #79
