### ISSUE TITLE
PhantomJs stacktrace errors

### ISSUE THREAD

**Issue by pjpsoares** [mgechev/angular2-seed#811]
When we have an error with the unit tests running on PhantomJS the stacktrace seems to be incomplete (we should have the line for the actual failure):
```
    Expected 'Features' to equal 'Featurees'.
    invoke@/Users/paulo/depot/personal/angular2-seed/node_modules/zone.js/dist/zone.js:323:34
    run@/Users/paulo/depot/personal/angular2-seed/node_modules/zone.js/dist/zone.js:216:50
    /Users/paulo/depot/personal/angular2-seed/node_modules/zone.js/dist/zone.js:571:61
    invokeTask@/Users/paulo/depot/personal/angular2-seed/node_modules/zone.js/dist/zone.js:356:43
    runTask@/Users/paulo/depot/personal/angular2-seed/node_modules/zone.js/dist/zone.js:256:58
    drainMicroTaskQueue@/Users/paulo/depot/personal/angular2-seed/node_modules/zone.js/dist/zone.js:474:43
    invoke@/Users/paulo/depot/personal/angular2-seed/node_modules/zone.js/dist/zone.js:426:41
    /Users/paulo/depot/personal/angular2-seed/node_modules/zone.js/dist/zone.js:93:33
    invokeTask@/Users/paulo/depot/personal/angular2-seed/node_modules/zone.js/dist/zone.js:356:43
    runTask@/Users/paulo/depot/personal/angular2-seed/node_modules/zone.js/dist/zone.js:256:58
    invoke@/Users/paulo/depot/personal/angular2-seed/node_modules/zone.js/dist/zone.js:423:41
```

For comparison, the same stacktrace on Chrome:
```
    Expected 'Features' to equal 'Featurees'.
        at eval (/Users/paulo/depot/personal/angular2-seed/dist/dev/app/+about/components/about.component.spec.js:21:103)
        at ZoneDelegate.invoke (/Users/paulo/depot/personal/angular2-seed/node_modules/zone.js/dist/zone.js:323:29)
        at Zone.run (/Users/paulo/depot/personal/angular2-seed/node_modules/zone.js/dist/zone.js:216:44)
        at /Users/paulo/depot/personal/angular2-seed/node_modules/zone.js/dist/zone.js:571:58
        at ZoneDelegate.invokeTask (/Users/paulo/depot/personal/angular2-seed/node_modules/zone.js/dist/zone.js:356:38)
        at Zone.runTask (/Users/paulo/depot/personal/angular2-seed/node_modules/zone.js/dist/zone.js:256:48)
        at drainMicroTaskQueue (/Users/paulo/depot/personal/angular2-seed/node_modules/zone.js/dist/zone.js:474:36)
        at XMLHttpRequest.ZoneTask.invoke (/Users/paulo/depot/personal/angular2-seed/node_modules/zone.js/dist/zone.js:426:22)
```

To reproduce, we just need to force a failure on a test.

**Comment by antonybudianto** [comment]
related to [this](https://github.com/karma-runner/karma-jasmine/issues/120), happens to my starter too
