### ISSUE TITLE
Unable to test obeservables

### ISSUE THREAD

**Issue by vijayaragavendiran** [mgechev/angular2-seed#819]
Hi,
I am trying to test Observable.  I am getting below error. Please guide me.

ERROR: 'Unhandled Promise rejection:', 'EXCEPTION: Error in :0:0
ORIGINAL EXCEPTION: No provider for Http!
ORIGINAL STACKTRACE:
Error: DI Exception
    at NoProviderError.BaseException [as constructor] (http://localhost:9876/base/node_modules/angular2/src/facade/exceptions.js:17:23)
    at NoProviderError.AbstractProviderError [as constructor] (http://localhost:9876/base/node_modules/angular2/src/core/di/reflective_exceptions.js:39:16)
    at new NoProviderError (http://localhost:9876/base/node_modules/angular2/src/core/di/reflective_exceptions.js:75:16)
    at ReflectiveInjector_._throwOrNull (http://localhost:9876/base/node_modules/angular2/src/core/di/reflective_injector.js:777:19)
    at ReflectiveInjector_._getByKeyDefault (http://localhost:9876/base/node_modules/angular2/src/core/di/reflective_injector.js:805:25)
    at ReflectiveInjector_._getByKey (http://localhost:9876/base/node_modules/angular2/src/core/di/reflective_injector.js:768:25)
    at ReflectiveInjector_.get (http://localhost:9876/base/node_modules/angular2/src/core/di/reflective_injector.js:577:21)
    at AppView.Object.defineProperty.get (TestComponent_Host.template.js:17:122)
    at AppView._View_TestComponent_Host0.injectorGetInternal (TestComponent_Host.template.js:34:84)
    at AppView.injectorGet (http://localhost:9876/base/node_modules/angular2/src/core/linker/view.js:120:29)
    at ElementInjector.get (http://localhost:9876/base/node_modules/angular2/src/core/linker/element_injector.js:21:33)
    at AppView._View_TestComponent0.createInternal (TestComponent.template.js:16:72)
    at AppView.create (http://localhost:9876/base/node_modules/angular2/src/core/linker/view.js:77:29)
    at AppView._View_TestComponent_Host0.createInternal (TestComponent_Host.template.js:27:14)
    at AppView.create (http://localhost:9876/base/node_modules/angular2/src/core/linker/view.js:77:29)
    at ComponentFactory.create (http://localhost:9876/base/node_modules/angular2/src/core/linker/component_factory.js:150:36)
    at eval (http://localhost:9876/base/node_modules/angular2/src/core/linker/dynamic_component_loader.js:36:49)
    at ZoneDelegate.invoke (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:323:29)
    at Zone.run (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:216:44)
    at http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:571:58
    at ZoneDelegate.invokeTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:356:38)
    at Zone.runTask (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:256:48)
    at drainMicroTaskQueue (http://localhost:9876/base/node_modules/zone.js/dist/zone.js?8b9c8d0a7e549abe9edec8da5a095f206d206277:474:36)

**Comment by ludohenin** [comment]
I think this fairly clear:

> ORIGINAL EXCEPTION: No provider for Http!

`HTTP` providers are missing somewhere in your test suite.
