### ISSUE TITLE
npm run-script serve.prod error

### ISSUE THREAD

**Issue by AntonyBaasan** [mgechev/angular2-seed#835]
Trying to deploy on Ubuntu 14.14.
"npm start" - works OK. 
Run the command "npm run-script serve.prod", getting below error.
Am I doing something wrong?
...
[11:47:44] Using gulpfile ~/projects/angular2-seed/gulpfile.ts
[11:47:44] Starting 'serve.prod'...
[11:47:44] Starting 'build.prod'...
[11:47:44] Starting 'clean.prod'...
[11:47:44] Deleted dist/prod
[11:47:44] Deleted dist/tmp
[11:47:44] Finished 'clean.prod' after 36 ms
[11:47:44] Starting 'tslint'...
[11:47:48] Finished 'tslint' after 4.05 s
[11:47:48] Starting 'css-lint'...
[11:47:50] Finished 'css-lint' after 1.75 s
[11:47:50] Starting 'build.assets.prod'...
[11:47:50] Finished 'build.assets.prod' after 73 ms
[11:47:50] Starting 'build.html_css'...
[11:47:51] Finished 'build.html_css' after 791 ms
[11:47:51] Starting 'copy.js.prod'...
[11:47:51] Finished 'copy.js.prod' after 41 ms
[11:47:51] Starting 'build.js.prod'...
[11:47:54] Finished 'build.js.prod' after 3.2 s
[11:47:54] Starting 'build.bundles'...
[11:47:57] Finished 'build.bundles' after 2.71 s
[11:47:57] Starting 'build.bundles.app'...
[11:48:15] Finished 'build.bundles.app' after 18 s
[11:48:15] Starting 'build.index.prod'...
[11:48:15] gulp-inject 2 files into index.html.
[11:48:15] gulp-inject 1 files into index.html.
[11:48:15] Finished 'build.index.prod' after 103 ms
[11:48:15] Finished 'build.prod' after 31 s
[11:48:15] Starting 'server.prod'...
[11:48:15] Finished 'server.prod' after 14 ms
[11:48:15] Finished 'serve.prod' after 31 s
Error: spawn ENOMEM
    at exports._errnoException (util.js:949:11)
    at ChildProcess.spawn (internal/child_process.js:302:11)
    at exports.spawn (child_process.js:367:9)
    at Object.exports.execFile (child_process.js:139:15)
    at exports.exec (child_process.js:99:18)
    at open (/home/safeuser/projects/angular2-seed/node_modules/open/lib/open.js:58:10)
    at Server.<anonymous> (server.ts:54:5)
    at Server.g (events.js:286:16)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:185:7)
    at emitListeningNT (net.js:1279:10)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

npm ERR! Linux 3.13.0-85-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run-script" "serve.prod"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! angular2-seed@0.0.0 serve.prod: `gulp serve.prod --color`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular2-seed@0.0.0 serve.prod script 'gulp serve.prod --color'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular2-seed package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     gulp serve.prod --color
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular2-seed
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular2-seed
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/safeuser/projects/angular2-seed/npm-debug.log

**Comment by NathanWalker** [comment]
@AntonyBaasan Have you tried just: `npm run serve.prod` ?
Is `run-script` a particular ubuntu thing?

**Comment by ludohenin** [comment]
@NathanWalker `run` is actually an alias of `run-script` npm command.

**Comment by NathanWalker** [comment]
@ludohenin Thanks 👍  Seems strange that ubuntu would be that different than OS X... not sure what's going on with his issue.

**Comment by AntonyBaasan** [comment]
Today I'll make a Vagrant script that anyone can test my situation.
@NathanWalker, what module is "**open**" /home/safeuser/projects/angular2-seed/node_modules/**open**/lib/open.js:58:10 ? I think I can dig from there.

**Comment by mgechev** [comment]
@AntonyBaasan 

> ENOMEM

> is an OS error code , as defined in kern/include/kern/errno.h ,which is returned due to insufficient memory.

Are you running the production build on a VM with limited memory? This seems like environment specific issue.

**Comment by AntonyBaasan** [comment]
Hi @mgechev, Yep you are right. It is environment specific.
Bad hardware: DigitalOcean 5$ stack - 1gb CPU, 512mb RAM
Good hardware: DigitalOcean 10$ stack - 1gb CPU, 1gb RAM

**Comment by mgechev** [comment]
Still, it is weird that 512MB RAM are not enough, there's also swap space on disk..

**Comment by ludohenin** [comment]
Might just be a bad node config, Max RAM should be set below the available amount (to keep a bit for te OS :))
