### ISSUE TITLE
Doesn't work with npm 3.x

### ISSUE THREAD

**Issue by mgechev** [mgechev/angular2-seed#89]
After the dependencies are installed with npm 3.x.x and I run `gulp serve.dev` I get:

```
[15:15:11] Finished 'serve.dev' after 13 ms
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: ENOENT, open '/Users/mgechev/Desktop/angular2-seed/node_modules/tiny-lr/node_modules/livereload-js/dist/livereload.js'
    at Error (native)
```

The issue is [caused by `tiny-lr`](https://github.com/mklabs/tiny-lr/issues/91).

**Comment by ludohenin** [comment]
@mgechev it works as it is for me with npm 3.x

**Comment by devmark** [comment]
using 3.x.x
npm install 
gulp serve.dev

I also get this error before. So i moved to npm 2.x

**Comment by mgechev** [comment]
@devmark would you test against this branch https://github.com/mgechev/angular2-seed/tree/npm3 and npm 3.x.x?

**Comment by devmark** [comment]
npm : 3.3.4

```
odule.js:338
    throw err;
    ^
Error: Cannot find module 'angular2/node_modules/traceur/bin/traceur-runtime.js'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.require.resolve (module.js:388:19)
    at Object.<anonymous> (/Volumes/Data/www/open-source/angular2-seed/gulpfile.js:65:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
```

**Comment by mgechev** [comment]
@devmark may be you forgot to `git checkout npm3`?
