### ISSUE TITLE
404 and Uncaught (in promise): Failed to load app/app.component.html

### ISSUE THREAD

**Issue by omargon** [mgechev/angular2-seed#893]
Hi,  I've being trying to setup an environment based on this seed, also including the sass integration wiki and incorporating the UI component ng2bootstrap and bootstrap 4 as well. I got dev and prod distribution builds working as expected but I'm still getting a test error that I can't find a solution for. Hope this is the right channel to get a solution, but if this is not the place to ask for support I will appreciate any directions. Below is the error I get every time I try to run the test. Here is a link to my project: https://github.com/omargon/angular-seed-sass-ng2-bootstrap

```
[21:42:44] Starting 'karma.start'...

START:
17 05 2016 21:42:45.636:INFO [karma]: Karma v0.13.22 server started at http://localhost:9876/
17 05 2016 21:42:45.642:INFO [launcher]: Starting browser PhantomJS
17 05 2016 21:42:45.654:INFO [launcher]: Starting browser Chrome
17 05 2016 21:42:46.297:INFO [PhantomJS 2.1.1 (Mac OS X 0.0.0)]: Connected on socket /#B-1fkZc8DS8JhZQTAAAA with id 19489448
17 05 2016 21:42:46.473:INFO [Chrome 50.0.2661 (Mac OS X 10.11.5)]: Connected on socket /#7Op8eDE_01kH-kHlAAAB with id 85662735
17 05 2016 21:42:47.420:WARN [web-server]: 404: /app/app.component.html
  NameList Service
    ✔ should return the list of names
17 05 2016 21:42:47.669:WARN [web-server]: 404: /app/app.component.html
  App component
    ✖ should build without a problem

Finished in 0.144 secs / 0.119 secs

SUMMARY:
✔ 2 tests completed
✖ 2 tests failed

FAILED TESTS:
  App component
    ✖ should build without a problem
      PhantomJS 2.1.1 (Mac OS X 0.0.0)
      Chrome 50.0.2661 (Mac OS X 10.11.5)
    Failed: Uncaught (in promise): Failed to load app/app.component.html
        at ZoneDelegate.invoke (/Users/omar/Development/pay-merchant-center/node_modules/zone.js/dist/zone.js:323:29)
        at Zone.run (/Users/omar/Development/pay-merchant-center/node_modules/zone.js/dist/zone.js:216:44)
        at /Users/omar/Development/pay-merchant-center/node_modules/zone.js/dist/zone.js:571:58
        at ZoneDelegate.invokeTask (/Users/omar/Development/pay-merchant-center/node_modules/zone.js/dist/zone.js:356:38)
        at Zone.runTask (/Users/omar/Development/pay-merchant-center/node_modules/zone.js/dist/zone.js:256:48)
        at drainMicroTaskQueue (/Users/omar/Development/pay-merchant-center/node_modules/zone.js/dist/zone.js:474:36)
        at F (/Users/omar/Development/pay-merchant-center/node_modules/systemjs/dist/system-polyfills.js:4:7484)
        at H (/Users/omar/Development/pay-merchant-center/node_modules/systemjs/dist/system-polyfills.js:4:7116)
        at q.when (/Users/omar/Development/pay-merchant-center/node_modules/systemjs/dist/system-polyfills.js:4:10790)
        at T.run (/Users/omar/Development/pay-merchant-center/node_modules/systemjs/dist/system-polyfills.js:4:11899)
        at t._drain (/Users/omar/Development/pay-merchant-center/node_modules/systemjs/dist/system-polyfills.js:4:1744)
        at drain (/Users/omar/Development/pay-merchant-center/node_modules/systemjs/dist/system-polyfills.js:4:1398)
        at MutationObserver.e (/Users/omar/Development/pay-merchant-center/node_modules/systemjs/dist/system-polyfills.js:4:3319)
```

**Comment by mgechev** [comment]
Great job! May be it is an issue with https://www.npmjs.com/package/gulp-inline-ng2-template ?

Take a look at the `useRelativePaths` option.

**Comment by omargon** [comment]
Thanks @mgechev. I looked into the gulp-inline-ng2-template options including useRelativePaths, but no luck.. I will keep searching for a solution or rebuild the base once again.

**Comment by TheDonDope** [comment]
Hi @omargon, take a look here: https://github.com/mgechev/angular2-seed/pull/891/commits (especially the two commits that update the gulp-inline-ng2-template configuration. Maybe this could be of help for you.

Greetings

Dope

**Comment by omargon** [comment]
Thanks @mgechev and @TheDonDope, indeed, after adding gulp-inline-ng2-template to the piping in build.js.test with the right configuration it fixed the error. Closing issue.

**Comment by TheDonDope** [comment]
@omargon Nice to hear! You are welcome! :)

**Comment by DarienF** [comment]
I find out that this error appear when framework can't build component html template. In cmd available only error 'Failed to load *.html' bot if you try to run you spec tests like here: [](http://plnkr.co/edit/EA3RL1b5OuW8SY5O5EEs?p=preview) it show you all errors witch prevent correct component html template build. My errors was: 'No provider for...', 'Component not in the module', ...after error fix tests run successfully. Problem is cmd not display specific error details

**Comment by Joonior1990** [comment]
I'm not sure but as option we can change: 

`
@Component({
  selection: anySelection,
  templateUrl: './my.template.html',
 styleUrls: [./my.styles.css']
})
` to `
@Component({
  selection: anySelection,
  template: require('./my.template.html'),
 styles: [ require('./my.styles.css')]
})
`

**Comment by MalTarDesigns** [comment]
Joonior1990  Your solution worked for me thanks!
