### ISSUE TITLE
gulp build.dev and gulp serve.dev fail with Error: Cannot find module

### ISSUE THREAD

**Issue by shershen08** [mgechev/angular2-seed#902]
May seem related to #711 but I have Nodejs 6.0.0, tsc 1.8.10, NPM 3.8.6 @ MacOS 10.11

 **$ sudo npm run build.dev**
gives error:
```
> angular2-seed@0.0.0 build.dev /Users/myaccount/angular-2-ts/angular2-seed
> gulp build.dev --color

(node:17291) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
[20:12:48] Loading tasks folder /Users/myaccount/angular-2-ts/angular2-seed/tools/tasks/seed
[20:12:48] Registering task /Users/myaccount/angular-2-ts/angular2-seed/tools/tasks/seed/build.assets.dev
[20:12:48] Registering task /Users/myaccount/angular-2-ts/angular2-seed/tools/tasks/seed/build.assets.prod
//..so on
[20:12:48] Loading tasks folder /Users/myaccount/angular-2-ts/angular2-seed/tools/tasks/project
[20:12:48] Registering task /Users/myaccount/angular-2-ts/angular2-seed/tools/tasks/project/sample.task
[20:12:48] Using gulpfile ~/angular-2-ts/angular2-seed/gulpfile.js
[20:12:48] Starting 'build.dev'...
[20:12:48] Starting 'clean.dev'...
[20:12:48] 'clean.dev' errored after 198 μs
[20:12:48] Error: Cannot find module '/Users/myaccount/angular-2-ts/angular2-seed/tools/tasks/seed/clean.dev'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Gulp.<anonymous> (/Users/myaccount/angular-2-ts/angular2-seed/tools/utils/seed/tasks_tools.js:16:20)
    at module.exports (/Users/myaccount/angular-2-ts/angular2-seed/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/myaccount/angular-2-ts/angular2-seed/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/myaccount/angular-2-ts/angular2-seed/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/myaccount/angular-2-ts/angular2-seed/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/Users/myaccount/angular-2-ts/angular2-seed/node_modules/run-sequence/index.js:86:16)```


, same goes to any task like ```gulp serve.dev --color```

**Comment by sfabriece** [comment]
Have you tried deleting node_modules adn typings directories. and npm init again?

**Comment by shershen08** [comment]
```npm update``` you mean? tried that, no luck

**Comment by TheDonDope** [comment]
Hi @shershen08, if it is not too much of a hassle, could you try to downgrade to Node 5.x, if it is still reproducable? If have a feeling that it might be a Node 6 related issue.

Greetings

Dope

**Comment by shershen08** [comment]
@TheDonDope , tried downgrading to 5.0.0, still having issues.

I've posted some relevant details here - http://stackoverflow.com/questions/37346512/how-to-fix-fs-re-evaluating-native-module-sources-is-not-supported-graceful)

Now I have **NPM 2.15.1, NodeJS v4.4.3**

and heres's current stacktrace
```
Using gulpfile ~/_Other/angular-2-ts/angular2-seed/gulpfile.js
[11:10:55] Starting 'serve.dev'...
[11:10:55] Starting 'build.dev'...
[11:10:55] Starting 'clean.dev'...
[11:10:55] 'clean.dev' errored after 677 μs
[11:10:55] Error: Cannot find module '/Users/myaccount/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/clean.dev'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Gulp.<anonymous> (/Users/myaccount/_Other/angular-2-ts/angular2-seed/tools/utils/seed/tasks_tools.js:16:20)
    at module.exports (/Users/myaccount/_Other/angular-2-ts/angular2-seed/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/myaccount/_Other/angular-2-ts/angular2-seed/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/myaccount/_Other/angular-2-ts/angular2-seed/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/myaccount/_Other/angular-2-ts/angular2-seed/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at runNextSet (/Users/myaccount/_Other/angular-2-ts/angular2-seed/node_modules/run-sequence/index.js:86:16)
```

**Comment by ludohenin** [comment]
@shershen08 It looks like `require` function is redefined at some point (looking for a `.js` file which doesn't exist instead of a `.ts`). It should be patched/replaced by `ts-node/register` but for reason at this point this is not working.
To workaround this issue, you can compile the tools with `npm run gulp -- build.tools` (to clean the folder up `npm run gulp -- clean.tools`).

**Comment by shershen08** [comment]
I've tried **npm run gulp -- clean.tools** and **npm run gulp -- build.tools** - but they both fail witht he same kind of output:
**$ npm run gulp -- clean.tools**

```
> angular2-seed@0.0.0 gulp /Users/myuserfolder/_Other/angular-2-ts/angular2-seed
> gulp "clean.tools"

[16:34:47] Loading tasks folder /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/build.assets.dev
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/build.assets.prod
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/build.bundles.app
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/build.bundles
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/build.docs
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/build.html_css
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/build.index.dev
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/build.index.prod
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/build.js.dev
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/build.js.e2e
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/build.js.prod
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/build.js.test
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/build.js.tools
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/check.versions
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/clean.all
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/clean.dev
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/clean.prod
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/clean.tools
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/copy.js.prod
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/css-lint
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/karma.start
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/serve.coverage
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/serve.docs
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/server.prod
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/server.start
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/tslint
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/watch.dev
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/watch.e2e
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/watch.test
[16:34:47] Loading tasks folder /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/project
[16:34:47] Registering task /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/project/sample.task
[16:34:47] Using gulpfile ~/_Other/angular-2-ts/angular2-seed/gulpfile.js
[16:34:47] Starting 'clean.tools'...
[16:34:47] 'clean.tools' errored after 182 μs
[16:34:47] Error: Cannot find module '/Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/tasks/seed/clean.tools'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Gulp.<anonymous> (/Users/myuserfolder/_Other/angular-2-ts/angular2-seed/tools/utils/seed/tasks_tools.js:16:20)
    at module.exports (/Users/myuserfolder/_Other/angular-2-ts/angular2-seed/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/myuserfolder/_Other/angular-2-ts/angular2-seed/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/myuserfolder/_Other/angular-2-ts/angular2-seed/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/myuserfolder/_Other/angular-2-ts/angular2-seed/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /Users/myuserfolder/_Other/angular-2-ts/angular2-seed/node_modules/gulp/bin/gulp.js:129:20

npm ERR! Darwin 15.4.0
npm ERR! argv "/usr/local/Cellar/node4-lts/4.4.4/bin/node" "/usr/local/bin/npm" "run" "gulp" "--" "clean.tools"
npm ERR! node v4.4.4
npm ERR! npm  v2.15.1
```

**Comment by shershen08** [comment]
@ludohenin thank you for the pointer - "It looks like require function is redefined at some point (looking for a .js file which doesn't exist instead of a .ts"
 - actually I had both gulpfile.js and gulpfile.ts in my directory!

## removing the **gulpfile.js** helped!

**Comment by ShaggyDude** [comment]
I am still having this issue with all versions of node I try. What is the --color?
